package eastangliamapserver;

import java.util.*;

public class SignalMap
{
    public static void createBerthObjects()
    {
        initStratford();
        initIlford();
        initShenfield();
        initWitham();
        initHackney();
        initHarlow();
        initColchester();
        initClacton();
        initIpswich();
        initCambridgeCA();
        initCambridgeEN();
        initNorwich();
    }

    //<editor-fold defaultstate="collapsed" desc="Norwich">
    private static void initNorwich()
    {
        Berths.createOrGetBerth("CC0392");
        Berths.createOrGetBerth("CC0393");
        Berths.createOrGetBerth("CC0395");
        Berths.createOrGetBerth("CC0396");
        Berths.createOrGetBerth("CC0413");
        Berths.createOrGetBerth("CC0415");
        Berths.createOrGetBerth("CC0416");
        Berths.createOrGetBerth("CC0422");
        Berths.createOrGetBerth("CC0423");
        Berths.createOrGetBerth("CC0424");
        Berths.createOrGetBerth("CC0427");
        Berths.createOrGetBerth("CC0429");
        Berths.createOrGetBerth("CC0430").setName("DIS Plat 2 Up");
        Berths.createOrGetBerth("CC0433").setName("DIS Plat 2 Dn");
        Berths.createOrGetBerth("CC0431").setName("DIS Plat 1");
        Berths.createOrGetBerth("CC0436");
        Berths.createOrGetBerth("CC0439");
        Berths.createOrGetBerth("CC0442");
        Berths.createOrGetBerth("CC0443");
        Berths.createOrGetBerth("CC0447");
        Berths.createOrGetBerth("CC0448");
        Berths.createOrGetBerth("CC0453");
        Berths.createOrGetBerth("CC0454");
        Berths.createOrGetBerth("CC0460");
        Berths.createOrGetBerth("CC0499");
        Berths.createOrGetBerth("CC0500");
        Berths.createOrGetBerth("CC0501");
        Berths.createOrGetBerth("CC0531");
        Berths.createOrGetBerth("CC0533");
        Berths.createOrGetBerth("CC0535");
        Berths.createOrGetBerth("CC0541");
        Berths.createOrGetBerth("CC0543");
        Berths.createOrGetBerth("CC0546");
        Berths.createOrGetBerth("CC0549");
        Berths.createOrGetBerth("CC0550");
        Berths.createOrGetBerth("CC0552");
        Berths.createOrGetBerth("CC0554");
        Berths.createOrGetBerth("CC0557");
        Berths.createOrGetBerth("CC0559");
        Berths.createOrGetBerth("CC0561");
        Berths.createOrGetBerth("CC0564");
        Berths.createOrGetBerth("CC0565");
        Berths.createOrGetBerth("CC0566");
        Berths.createOrGetBerth("CC0567");
        Berths.createOrGetBerth("CC0570");
        Berths.createOrGetBerth("CC0572");
        Berths.createOrGetBerth("CC0574").setName("NRW Plat 1");
        Berths.createOrGetBerth("CC0576").setName("NRW Plat 2");
        Berths.createOrGetBerth("CC0578").setName("NRW Plat 3");
        Berths.createOrGetBerth("CC0580").setName("NRW Plat 4");
        Berths.createOrGetBerth("CC0584").setName("NRW Plat 5");
        Berths.createOrGetBerth("CC0586").setName("NRW Plat 6");
        Berths.createOrGetBerth("CC0588");
        Berths.createOrGetBerth("CC0679");
        Berths.createOrGetBerth("CC0680").addStepToBerth("CC0680", "CCB050", "CCBURD", "interpose");
        Berths.createOrGetBerth("CC0689");
        Berths.createOrGetBerth("CC0691");
        Berths.createOrGetBerth("CC0692");
        Berths.createOrGetBerth("CC0698");
        Berths.createOrGetBerth("CC0699");
        Berths.createOrGetBerth("CC0877");
        Berths.createOrGetBerth("CC0878").addStepToBerth("CC0878", "EN8246", "CC8246", "suggest");
        Berths.createOrGetBerth("CC0889");
        Berths.createOrGetBerth("CC0890");
        Berths.createOrGetBerth("CC0891");
        Berths.createOrGetBerth("CC1413");
        Berths.createOrGetBerth("CC1408");
        Berths.createOrGetBerth("CC1409");
        Berths.createOrGetBerth("CC1411");
        Berths.createOrGetBerth("CC1416");
        Berths.createOrGetBerth("CC1491");
        Berths.createOrGetBerth("CC1574").setName("NRW Plat 1");
        Berths.createOrGetBerth("CC1576").setName("NRW Plat 2");
        Berths.createOrGetBerth("CC1578").setName("NRW Plat 3");
        Berths.createOrGetBerth("CC1580").setName("NRW Plat 4");
        Berths.createOrGetBerth("CC1584").setName("NRW Plat 5");
        Berths.createOrGetBerth("CC1586").setName("NRW Plat 6");
        Berths.createOrGetBerth("CC1762");
        Berths.createOrGetBerth("CC1792");
        Berths.createOrGetBerth("CC8237"); // CBG sig on NRW panel
        Berths.createOrGetBerth("CC8246"); // CBG sig on NRW panel
        Berths.createOrGetBerth("CCBL03");
        Berths.createOrGetBerth("CCBL28");
        Berths.createOrGetBerth("CCBURD");
        Berths.createOrGetBerth("CCCPT1");
        Berths.createOrGetBerth("CCCPT2");
        Berths.createOrGetBerth("CCCSDG");
        Berths.createOrGetBerth("CCENGN");
        Berths.createOrGetBerth("CCFUEL");
        Berths.createOrGetBerth("CCL533");
        Berths.createOrGetBerth("CCL535");
        Berths.createOrGetBerth("CCLSR1");
        Berths.createOrGetBerth("CCLSR2");
        Berths.createOrGetBerth("CCJUBS");
        Berths.createOrGetBerth("CCR574").setName("NRW Plat 1");
        Berths.createOrGetBerth("CCR576").setName("NRW Plat 2");
        Berths.createOrGetBerth("CCR578").setName("NRW Plat 3");
        Berths.createOrGetBerth("CCR580").setName("NRW Plat 4");
        Berths.createOrGetBerth("CCR584").setName("NRW Plat 5");
        Berths.createOrGetBerth("CCR586").setName("NRW Plat 6");
        Berths.createOrGetBerth("CCTB02");
        Berths.createOrGetBerth("CCTB03");
        Berths.createOrGetBerth("CCTB04");
        Berths.createOrGetBerth("CCTB05");
        Berths.createOrGetBerth("CCTB06");
        Berths.createOrGetBerth("CCTB09");
        Berths.createOrGetBerth("CCTB10");
        Berths.createOrGetBerth("CCTB13");
        Berths.createOrGetBerth("CCTB14");
        Berths.createOrGetBerth("CCTB17");
        Berths.createOrGetBerth("CCTB18");
        Berths.createOrGetBerth("CCTB21");
        Berths.createOrGetBerth("CCTB25");
        Berths.createOrGetBerth("CCTB26");
        Berths.createOrGetBerth("CCTB28");
        Berths.createOrGetBerth("CCTB31");
        Berths.createOrGetBerth("CCTB32");
        Berths.createOrGetBerth("CCTB33");
        Berths.createOrGetBerth("CCTB34");
        Berths.createOrGetBerth("CCHSSD");
        Berths.createOrGetBerth("CCMSDG");
        Berths.createOrGetBerth("CCX034");
        Berths.createOrGetBerth("CCX032");
        Berths.createOrGetBerth("CCYARD");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Cambridge (EN)">
    private static void initCambridgeEN()
    {
        //NRW - ELY
        Berths.createOrGetBerth("ENA808");
        Berths.createOrGetBerth("ENC877");
        Berths.createOrGetBerth("EN8019");
        Berths.createOrGetBerth("EN8024").addStepToBerth("EN8024", "CA0808", "ENA808", "suggest");
        Berths.createOrGetBerth("EN8034");
        Berths.createOrGetBerth("EN8041");
        Berths.createOrGetBerth("EN8044");
        Berths.createOrGetBerth("EN8061");
        Berths.createOrGetBerth("EN8063");
        Berths.createOrGetBerth("EN8064");
        Berths.createOrGetBerth("EN8066");
        Berths.createOrGetBerth("EN8069");
        Berths.createOrGetBerth("EN8078");
        Berths.createOrGetBerth("EN8081");
        Berths.createOrGetBerth("EN8083");
        Berths.createOrGetBerth("EN8084");
        Berths.createOrGetBerth("EN8086");
        Berths.createOrGetBerth("EN8103");
        Berths.createOrGetBerth("EN8104");
        Berths.createOrGetBerth("EN8109");
        Berths.createOrGetBerth("EN8110");
        Berths.createOrGetBerth("EN8113");
        Berths.createOrGetBerth("EN8118");
        Berths.createOrGetBerth("EN8114");
        Berths.createOrGetBerth("EN8129");
        Berths.createOrGetBerth("EN8134");
        Berths.createOrGetBerth("EN8148");
        Berths.createOrGetBerth("EN8149");
        Berths.createOrGetBerth("EN8153");
        Berths.createOrGetBerth("EN8155");
        Berths.createOrGetBerth("EN8158");
        Berths.createOrGetBerth("EN8164");
        Berths.createOrGetBerth("EN8167");
        Berths.createOrGetBerth("EN8173");
        Berths.createOrGetBerth("EN8176");
        Berths.createOrGetBerth("EN8177");
        Berths.createOrGetBerth("EN8178");
        Berths.createOrGetBerth("EN8179");
        Berths.createOrGetBerth("EN8195");
        Berths.createOrGetBerth("EN8198");
        Berths.createOrGetBerth("EN8219");
        Berths.createOrGetBerth("EN8221");
        Berths.createOrGetBerth("EN8223");
        Berths.createOrGetBerth("EN8225");
        Berths.createOrGetBerth("EN8230");
        Berths.createOrGetBerth("EN8234");
        Berths.createOrGetBerth("EN8236");
        Berths.createOrGetBerth("EN8237").addStepToBerth("EN8237", "CC0877", "ENC877", "suggest");
        Berths.createOrGetBerth("EN8246");

        //KLN - ELY
        Berths.createOrGetBerth("CAK22A");
        Berths.createOrGetBerth("CAK22B");
        Berths.createOrGetBerth("CAK22R");
        Berths.createOrGetBerth("CAK23A");
        Berths.createOrGetBerth("CAK23B");
        Berths.createOrGetBerth("CAK23R");
        Berths.createOrGetBerth("CAKL7A");
        Berths.createOrGetBerth("CAKL24");
        Berths.createOrGetBerth("CAKL25");
        Berths.createOrGetBerth("CAKL35");
        Berths.createOrGetBerth("CAKL36");
        Berths.createOrGetBerth("CAKL43");
        Berths.createOrGetBerth("CAKL44");
        Berths.createOrGetBerth("CAKL45");
        Berths.createOrGetBerth("CADM02");
        Berths.createOrGetBerth("CADM03");
        Berths.createOrGetBerth("CADM11");
        Berths.createOrGetBerth("CADM26");
        Berths.createOrGetBerth("CADM27");
        Berths.createOrGetBerth("CALDAP");
        Berths.createOrGetBerth("CALT04");
        Berths.createOrGetBerth("CALT05");
        Berths.createOrGetBerth("CALT06");
        Berths.createOrGetBerth("CALT22");
        Berths.createOrGetBerth("CALT24");
        Berths.createOrGetBerth("CAMR01");
        Berths.createOrGetBerth("CAMR02");
        Berths.createOrGetBerth("CAMR03");
        Berths.createOrGetBerth("CAMR04");
        Berths.createOrGetBerth("CAMR05");
        Berths.createOrGetBerth("CAMR06");
        Berths.createOrGetBerth("CAMUAP");

        //MNE - ELY
        Berths.createOrGetBerth("CA0301");
        Berths.createOrGetBerth("CA0908");
        Berths.createOrGetBerth("CA0911");
        Berths.createOrGetBerth("CA0912");
        Berths.createOrGetBerth("CA0915");
        Berths.createOrGetBerth("CA0916");
        Berths.createOrGetBerth("CA0917");
        Berths.createOrGetBerth("CA0919");
        Berths.createOrGetBerth("CA0920");
        Berths.createOrGetBerth("CA0921");
        Berths.createOrGetBerth("CA0922");
        Berths.createOrGetBerth("CA0923");
        Berths.createOrGetBerth("CA0924");
        Berths.createOrGetBerth("CAM043");
        Berths.createOrGetBerth("CAM002");
        Berths.createOrGetBerth("CAM021");
        Berths.createOrGetBerth("CAM003");

        //Ely North Jnc
        Berths.createOrGetBerth("CA0296");
        Berths.createOrGetBerth("CA0298");
        Berths.createOrGetBerth("CA0303");
        Berths.createOrGetBerth("CA0305");
        Berths.createOrGetBerth("CA0306");
        Berths.createOrGetBerth("CA0307");
        Berths.createOrGetBerth("CA0308");
        Berths.createOrGetBerth("CA0311");
        Berths.createOrGetBerth("CA0774");
        Berths.createOrGetBerth("CA0800");
        Berths.createOrGetBerth("CA0801");
        Berths.createOrGetBerth("CA0802");
        Berths.createOrGetBerth("CA0803").addStepToBerth("CA0803", "EN8019", "CA8019", "suggest");
        Berths.createOrGetBerth("CA0804");
        Berths.createOrGetBerth("CA0808");
        Berths.createOrGetBerth("CA8019");
        Berths.createOrGetBerth("CALAPP");
        Berths.createOrGetBerth("CALSCM");
        Berths.createOrGetBerth("CAR4AB");
        Berths.createOrGetBerth("CASAPP");

        //BSE - CBG & ELY
        Berths.createOrGetBerth("CA0401");
        Berths.createOrGetBerth("CA0402");
        Berths.createOrGetBerth("CA0483");
        Berths.createOrGetBerth("CA0486");
        Berths.createOrGetBerth("CA0488");
        Berths.createOrGetBerth("CA0491");
        Berths.createOrGetBerth("CA0494");
        Berths.createOrGetBerth("CA0495");
        Berths.createOrGetBerth("CA0498");
        Berths.createOrGetBerth("CCB001");
        Berths.createOrGetBerth("CCB002");
        Berths.createOrGetBerth("CCB013");
        Berths.createOrGetBerth("CCB017");
        Berths.createOrGetBerth("CCB019");
        Berths.createOrGetBerth("CCB032");
        Berths.createOrGetBerth("CCB033");
        Berths.createOrGetBerth("CCB048");
        Berths.createOrGetBerth("CCB049");
        Berths.createOrGetBerth("CCB050");
        Berths.createOrGetBerth("CCB302").addStepToBerth("CCB302", "CACM14", "cancel", "suggest");
        Berths.createOrGetBerth("CCB303");
        Berths.createOrGetBerth("CCB306");
        Berths.createOrGetBerth("CCB307");
        Berths.createOrGetBerth("CCB310");
        Berths.createOrGetBerth("CACM02");
        Berths.createOrGetBerth("CACM04");
        Berths.createOrGetBerth("CACM05").addStepToBerth("CACM05", "CCB303", "cancel", "suggest");
        Berths.createOrGetBerth("CACM14");
        Berths.createOrGetBerth("CACAPP");
        Berths.createOrGetBerth("CAD002");
        Berths.createOrGetBerth("CAD003");
        Berths.createOrGetBerth("CAD004");
        Berths.createOrGetBerth("CAD005");
        Berths.createOrGetBerth("CAX200");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Cambridge (CA)">
    private static void initCambridgeCA()
    {
        Berths.createOrGetBerth("CA0019");
        Berths.createOrGetBerth("CA0020").addStepToBerth("CA0020", "WG1188", "CAL188", "suggest");
        Berths.createOrGetBerth("CA0021");
        Berths.createOrGetBerth("CA0022");
        Berths.createOrGetBerth("CA0023");
        Berths.createOrGetBerth("CA0024");
        Berths.createOrGetBerth("CA0026");
        Berths.createOrGetBerth("CA0027");
        Berths.createOrGetBerth("CA0028");
        Berths.createOrGetBerth("CA0029");
        Berths.createOrGetBerth("CA0030");
        Berths.createOrGetBerth("CA0031");
        Berths.createOrGetBerth("CA0032");
        Berths.createOrGetBerth("CA0033");
        Berths.createOrGetBerth("CA0034");
        Berths.createOrGetBerth("CA0037");
        Berths.createOrGetBerth("CA0038");
        Berths.createOrGetBerth("CA0039");
        Berths.createOrGetBerth("CA0040");
        Berths.createOrGetBerth("CA0041");
        Berths.createOrGetBerth("CA0042");
        Berths.createOrGetBerth("CA0043");
        Berths.createOrGetBerth("CA0044");
        Berths.createOrGetBerth("CA0047");
        Berths.createOrGetBerth("CA0045");
        Berths.createOrGetBerth("CA0050");
        Berths.createOrGetBerth("CA0051");
        Berths.createOrGetBerth("CA0052");
        Berths.createOrGetBerth("CA0053");
        Berths.createOrGetBerth("CA0054");
        Berths.createOrGetBerth("CA0055");
        Berths.createOrGetBerth("CA0056");
        Berths.createOrGetBerth("CA0057");
        Berths.createOrGetBerth("CA0058");
        Berths.createOrGetBerth("CA0059");
        Berths.createOrGetBerth("CA0060");
        Berths.createOrGetBerth("CA0061");
        Berths.createOrGetBerth("CA0062");
        Berths.createOrGetBerth("CA0064");
        Berths.createOrGetBerth("CA0066");
        Berths.createOrGetBerth("CA0067");
        Berths.createOrGetBerth("CA0072");
        Berths.createOrGetBerth("CA0073");
        Berths.createOrGetBerth("CA0074");
        Berths.createOrGetBerth("CA0075");
        Berths.createOrGetBerth("CA0076");
        Berths.createOrGetBerth("CA0077");
        Berths.createOrGetBerth("CA0079");
        Berths.createOrGetBerth("CAL187");
        Berths.createOrGetBerth("CAL188");

        Berths.createOrGetBerth("CA0078");
        Berths.createOrGetBerth("CA0080");
        Berths.createOrGetBerth("CA0082");
        Berths.createOrGetBerth("CA0083");
        Berths.createOrGetBerth("CA0084");
        Berths.createOrGetBerth("CA0085");
        Berths.createOrGetBerth("CA0087");
        Berths.createOrGetBerth("CA0090");
        Berths.createOrGetBerth("CA0091");
        Berths.createOrGetBerth("CA0092");
        Berths.createOrGetBerth("CA0093");
        Berths.createOrGetBerth("CA0094");
        Berths.createOrGetBerth("CA0095");
        Berths.createOrGetBerth("CA0096");
        Berths.createOrGetBerth("CA0097");
        Berths.createOrGetBerth("CA0099");
        Berths.createOrGetBerth("CA0100");
        Berths.createOrGetBerth("CA0103");
        Berths.createOrGetBerth("CA0104");
        Berths.createOrGetBerth("CA0105");
        Berths.createOrGetBerth("CA0106");
        Berths.createOrGetBerth("CA0107");
        Berths.createOrGetBerth("CA0108");
        Berths.createOrGetBerth("CA0109");
        Berths.createOrGetBerth("CA0110");
        Berths.createOrGetBerth("CA0113");
        Berths.createOrGetBerth("CA0114");
        Berths.createOrGetBerth("CA0115");
        Berths.createOrGetBerth("CA0116");
        Berths.createOrGetBerth("CA0117");
        Berths.createOrGetBerth("CA0118");
        Berths.createOrGetBerth("CA0119");
        Berths.createOrGetBerth("CA0120");
        Berths.createOrGetBerth("CA0123");
        Berths.createOrGetBerth("CA0140");
        Berths.createOrGetBerth("CA0141");
        Berths.createOrGetBerth("CA0142");
        Berths.createOrGetBerth("CA0143");
        Berths.createOrGetBerth("CA0144");
        Berths.createOrGetBerth("CA0145");
        Berths.createOrGetBerth("CA0147");
        Berths.createOrGetBerth("CA0148");
        Berths.createOrGetBerth("CA0149");
        Berths.createOrGetBerth("CA0150").setName("CBG Plat 3");
        Berths.createOrGetBerth("CA0152").setName("CBG Plat 2");
        Berths.createOrGetBerth("CA0154").setName("CBG Plat 1 Up");
        Berths.createOrGetBerth("CA0156");
        Berths.createOrGetBerth("CA0158").setName("CBG Plat 7 Up");
        Berths.createOrGetBerth("CA0160").setName("CBG Plat 8 Up");
        Berths.createOrGetBerth("CA0161").setName("CBG Plat 1 Dn");
        Berths.createOrGetBerth("CA0162").setName("CBG Plat 4 Up");
        Berths.createOrGetBerth("CA0163");
        Berths.createOrGetBerth("CA0164");
        Berths.createOrGetBerth("CA0171").setName("CBG Plat 6");
        Berths.createOrGetBerth("CA0173").setName("CBG Plat 5");
        Berths.createOrGetBerth("CA0175").setName("CBG Plat 4 Dn");
        Berths.createOrGetBerth("CA0177");
        Berths.createOrGetBerth("CA0179").setName("CBG Plat 7 Dn");
        Berths.createOrGetBerth("CA0181").setName("CBG Plat 8 Dn");
        Berths.createOrGetBerth("CA0180");
        Berths.createOrGetBerth("CA0188");
        Berths.createOrGetBerth("CA0190");
        Berths.createOrGetBerth("CA0193");
        Berths.createOrGetBerth("CA0195");
        Berths.createOrGetBerth("CA0200");
        Berths.createOrGetBerth("CA0210");
        Berths.createOrGetBerth("CA0653");
        Berths.createOrGetBerth("CA0655");
        Berths.createOrGetBerth("CADAPP");
        Berths.createOrGetBerth("CAX150").setName("CBG Plat 3");
        Berths.createOrGetBerth("CAX152").setName("CBG Plat 2");
        Berths.createOrGetBerth("CAX171").setName("CBG Plat 6");
        Berths.createOrGetBerth("CAX173").setName("CBG Plat 5");
        Berths.createOrGetBerth("CA0981");
        Berths.createOrGetBerth("CA0986");

        Berths.createOrGetBerth("CA0211");
        Berths.createOrGetBerth("CA0212");
        Berths.createOrGetBerth("CA0220");
        Berths.createOrGetBerth("CA0223");
        Berths.createOrGetBerth("CA0225");
        Berths.createOrGetBerth("CA0228");
        Berths.createOrGetBerth("CA0229");
        Berths.createOrGetBerth("CA0230");
        Berths.createOrGetBerth("CA0231");
        Berths.createOrGetBerth("CA0232");
        Berths.createOrGetBerth("CA0235");
        Berths.createOrGetBerth("CA0236");
        Berths.createOrGetBerth("CA0237");
        Berths.createOrGetBerth("CA0238");
        Berths.createOrGetBerth("CA0239");
        Berths.createOrGetBerth("CA0240");
        Berths.createOrGetBerth("CA0241");
        Berths.createOrGetBerth("CA0244");
        Berths.createOrGetBerth("CA0245");
        Berths.createOrGetBerth("CA0246");
        Berths.createOrGetBerth("CA0247");
        Berths.createOrGetBerth("CA0248");
        Berths.createOrGetBerth("CA0249");
        Berths.createOrGetBerth("CA0250");
        Berths.createOrGetBerth("CA0251");
        Berths.createOrGetBerth("CA0252");
        Berths.createOrGetBerth("CA0253");
        Berths.createOrGetBerth("CA0254");
        Berths.createOrGetBerth("CA0255");
        Berths.createOrGetBerth("CA0257");
        Berths.createOrGetBerth("CA0259");
        Berths.createOrGetBerth("CA0262");
        Berths.createOrGetBerth("CA0270");
        Berths.createOrGetBerth("CA0271");
        Berths.createOrGetBerth("CA0272");
        Berths.createOrGetBerth("CA0273");
        Berths.createOrGetBerth("CA0274").setName("ELY Plat 3 Up");
        Berths.createOrGetBerth("CA0276").setName("ELY Plat 2 Up");
        Berths.createOrGetBerth("CA0278").setName("ELY Plat 1 Up");
        Berths.createOrGetBerth("CA0281").setName("ELY Plat 1 Dn");
        Berths.createOrGetBerth("CA0283").setName("ELY Plat 2 Dn");
        Berths.createOrGetBerth("CA0285").setName("ELY Plat 3 Dn");
        Berths.createOrGetBerth("CA0287");
        Berths.createOrGetBerth("CA0288");
        Berths.createOrGetBerth("CA0290");
        Berths.createOrGetBerth("CA0293");
        Berths.createOrGetBerth("CA0295");
        Berths.createOrGetBerth("CA0765");
        Berths.createOrGetBerth("CA1765");
        Berths.createOrGetBerth("CA1273");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Ipswich">
    private static void initIpswich()
    {
        Berths.createOrGetBerth("CC0290");
        Berths.createOrGetBerth("CC0295");
        Berths.createOrGetBerth("CC0292");
        Berths.createOrGetBerth("CC0294");
        Berths.createOrGetBerth("CC0297");
        Berths.createOrGetBerth("CC0302").setName("IPS Plat 4 Up");
        Berths.createOrGetBerth("CC0304").setName("IPS Plat 3 Up (DM)");
        Berths.createOrGetBerth("CC0306").setName("IPS Up (TL)");
        Berths.createOrGetBerth("CC0308").setName("IPS Plat 2 Up (U&DL)");
        Berths.createOrGetBerth("CC0311").setName("IPS Plat 4 Dn");
        Berths.createOrGetBerth("CC0313").setName("IPS Plat 3 Dn (DM)");
        Berths.createOrGetBerth("CC0315").setName("IPS Dn (TL)");
        Berths.createOrGetBerth("CC0317").setName("IPS Plat 2 Dn (U&DL)");
        Berths.createOrGetBerth("CC0319").setName("IPS Plat 1");
        Berths.createOrGetBerth("CC0322");
        Berths.createOrGetBerth("CC0337");
        Berths.createOrGetBerth("CC0326");
        Berths.createOrGetBerth("CC0328");
        Berths.createOrGetBerth("CC0331");
        Berths.createOrGetBerth("CC0333");
        Berths.createOrGetBerth("CC0335");
        Berths.createOrGetBerth("CC0341");
        Berths.createOrGetBerth("CC0343");
        Berths.createOrGetBerth("CC0346");
        Berths.createOrGetBerth("CC0348");
        Berths.createOrGetBerth("CC0351");
        Berths.createOrGetBerth("CC0352");
        Berths.createOrGetBerth("CC0366");
        Berths.createOrGetBerth("CC0367");
        Berths.createOrGetBerth("CC0369");
        Berths.createOrGetBerth("CC0370");
        Berths.createOrGetBerth("CC0371");
        Berths.createOrGetBerth("CC0374");
        Berths.createOrGetBerth("CC0375");
        Berths.createOrGetBerth("CC0377");
        Berths.createOrGetBerth("CC1372");
        Berths.createOrGetBerth("CC0378");
        Berths.createOrGetBerth("CC0379");
        Berths.createOrGetBerth("CC0380").setName("NMT (UM)");
        Berths.createOrGetBerth("CC0381");
        Berths.createOrGetBerth("CC0383").setName("NMT (DM)");
        Berths.createOrGetBerth("CC0384");
        Berths.createOrGetBerth("CC0385");
        Berths.createOrGetBerth("CC0386");
        Berths.createOrGetBerth("CC0388").setName("SMK Plat 1 (UM)");
        Berths.createOrGetBerth("CC0389");
        Berths.createOrGetBerth("CC0391").setName("SMK Plat 2 (DM) Dn");
        Berths.createOrGetBerth("CC0390").setName("SMK Plat 2 (DM) Up");
        Berths.createOrGetBerth("CC0400");
        Berths.createOrGetBerth("CC0401");
        Berths.createOrGetBerth("CC0403");
        Berths.createOrGetBerth("CC0404");
        Berths.createOrGetBerth("CC0405");
        Berths.createOrGetBerth("CC0611").addStepToBerth("CC0611", "SX2003", "CC2003", "suggest");
        Berths.createOrGetBerth("CC0612").setName("WFI (UES)");
        Berths.createOrGetBerth("CC0613");
        Berths.createOrGetBerth("CC0614");
        Berths.createOrGetBerth("CC0615").setName("DBR (DF)");
        Berths.createOrGetBerth("CC0616");
        Berths.createOrGetBerth("CC0617");
        Berths.createOrGetBerth("CC0618").setName("DBR (UF)");
        Berths.createOrGetBerth("CC0619");
        Berths.createOrGetBerth("CC0620");
        Berths.createOrGetBerth("CC0621");
        Berths.createOrGetBerth("CC0622");
        Berths.createOrGetBerth("CC0624");
        Berths.createOrGetBerth("CC0626");
        Berths.createOrGetBerth("CC0632");
        Berths.createOrGetBerth("CC0634");
        Berths.createOrGetBerth("CC0641");
        Berths.createOrGetBerth("CC0642");
        Berths.createOrGetBerth("CC0644");
        Berths.createOrGetBerth("CC0797");
        Berths.createOrGetBerth("CC0799");
        Berths.createOrGetBerth("CCLOCS");
        Berths.createOrGetBerth("CC0812");
        Berths.createOrGetBerth("CC0814");
        Berths.createOrGetBerth("CC0816");
        Berths.createOrGetBerth("CC0818");
        Berths.createOrGetBerth("CC0827");
        Berths.createOrGetBerth("CC0829");
        Berths.createOrGetBerth("CC0831");
        Berths.createOrGetBerth("CC0834");
        Berths.createOrGetBerth("CC0835");
        Berths.createOrGetBerth("CC0841");
        Berths.createOrGetBerth("CC1319").setName("IPS Plat 1");
        Berths.createOrGetBerth("CC2003");
        Berths.createOrGetBerth("CC2012");
        Berths.createOrGetBerth("CCBARS");
        Berths.createOrGetBerth("CCFDAP");
        Berths.createOrGetBerth("CCFDLS");
        Berths.createOrGetBerth("CCFTSN").setName("FLX (U&DF)");
        Berths.createOrGetBerth("CCIPYA");
        Berths.createOrGetBerth("CCNQ02");
        Berths.createOrGetBerth("CCNQ04");
        Berths.createOrGetBerth("CCR290");
        Berths.createOrGetBerth("CCR388");
        Berths.createOrGetBerth("CCSDCR");
        Berths.createOrGetBerth("CCSDG1");
        Berths.createOrGetBerth("CCSDG2");
        Berths.createOrGetBerth("CCULAP");

        Berths.createOrGetBerth("SX2003").setName("WFI (DES)");
        Berths.createOrGetBerth("SX2004").addStepToBerth("SX2004", "CC0614", "SXC614", "suggest").setName("WDB (UES)");
        Berths.createOrGetBerth("SX2006").setName("WDB (DES)");
        Berths.createOrGetBerth("SX2011").setName("WDB (DES)");
        Berths.createOrGetBerth("SX2012");
        Berths.createOrGetBerth("SX2028").setName("SAX Plat 1 (UES)");
        Berths.createOrGetBerth("SX2029");
        Berths.createOrGetBerth("SX2032");
        Berths.createOrGetBerth("SX2033").setName("SAX Plat 2 (DES)");
        Berths.createOrGetBerth("SX2035");
        Berths.createOrGetBerth("SX2042");
        Berths.createOrGetBerth("SX2045").setName("HAS Plat 2 (DES)");
        Berths.createOrGetBerth("SX2046").setName("HAS Plat 1 (UES)");
        Berths.createOrGetBerth("SX2052");
        Berths.createOrGetBerth("SX2055");
        Berths.createOrGetBerth("SX2056").setName("BCC Plat 2 (UBL)");
        Berths.createOrGetBerth("SX2057").setName("BCC Plat 1 (DBL)");
        Berths.createOrGetBerth("SX2058").setName("BCC Plat 1 (DBL)");
        Berths.createOrGetBerth("SX2060");
        Berths.createOrGetBerth("SX2066").setName("OUS Up (U&DES)");
        Berths.createOrGetBerth("SXB21R");
        Berths.createOrGetBerth("SXC405");
        Berths.createOrGetBerth("SXC611");
        Berths.createOrGetBerth("SXC612");
        Berths.createOrGetBerth("SXC614");
        Berths.createOrGetBerth("SXLSOB");
        Berths.createOrGetBerth("SXOB18");
        Berths.createOrGetBerth("SXOB19").setName("OUS Dn (U&DES)");
        Berths.createOrGetBerth("SXOB21");
        Berths.createOrGetBerth("SXOSTO");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Clacton">
    private static void initClacton()
    {
        Berths.createOrGetBerth("CC1088");
        Berths.createOrGetBerth("CC1091");
        Berths.createOrGetBerth("CC1092");
        Berths.createOrGetBerth("CC1093");
        Berths.createOrGetBerth("CC1094");
        Berths.createOrGetBerth("CC1095");
        Berths.createOrGetBerth("CC1096");
        Berths.createOrGetBerth("CC1099");
        Berths.createOrGetBerth("CC1100");
        Berths.createOrGetBerth("CC1101");
        Berths.createOrGetBerth("CC1102");
        Berths.createOrGetBerth("CC1103");
        Berths.createOrGetBerth("CC1104");
        Berths.createOrGetBerth("CC1105");
        Berths.createOrGetBerth("CC1109");
        Berths.createOrGetBerth("CC1110");
        Berths.createOrGetBerth("CC1111");
        Berths.createOrGetBerth("CC1114");
        Berths.createOrGetBerth("CC1115");
        Berths.createOrGetBerth("CC1118");
        Berths.createOrGetBerth("CC1121");
        Berths.createOrGetBerth("CC1122");
        Berths.createOrGetBerth("CC1125");
        Berths.createOrGetBerth("CC1128");
        Berths.createOrGetBerth("CC1133");
        Berths.createOrGetBerth("CC1134");
        Berths.createOrGetBerth("CC1136");
        Berths.createOrGetBerth("CC1137");
        Berths.createOrGetBerth("CC1138");
        Berths.createOrGetBerth("CC1144");
        Berths.createOrGetBerth("CC1145");
        Berths.createOrGetBerth("CC1146");
        Berths.createOrGetBerth("CC1147");
        Berths.createOrGetBerth("CC1152");
        Berths.createOrGetBerth("CC1154");
        Berths.createOrGetBerth("CC1157");
        Berths.createOrGetBerth("CC1172");
        Berths.createOrGetBerth("CC1173");
        Berths.createOrGetBerth("CC1174");
        Berths.createOrGetBerth("CC1176");
        Berths.createOrGetBerth("CC1177");
        Berths.createOrGetBerth("CCAPP1");
        Berths.createOrGetBerth("CCAPP2");
        Berths.createOrGetBerth("CCR096");

        Berths.createOrGetBerth("CC1158");
        Berths.createOrGetBerth("CC1159");
        Berths.createOrGetBerth("CC1160");
        Berths.createOrGetBerth("CC1164");
        Berths.createOrGetBerth("CC1165");
        Berths.createOrGetBerth("CC1168");
        Berths.createOrGetBerth("CCWARR");

        Berths.createOrGetBerth("CCCN26");
        Berths.createOrGetBerth("CCCN27");
        Berths.createOrGetBerth("CCCN42");
        Berths.createOrGetBerth("CCCN44");
        Berths.createOrGetBerth("CCCN48");
        Berths.createOrGetBerth("CCCN55");
        Berths.createOrGetBerth("CCCN60");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Colchester">
    private static void initColchester()
    {
        Berths.createOrGetBerth("CC0190");
        Berths.createOrGetBerth("CC0191");
        Berths.createOrGetBerth("CC0194").setName("MNG Plat 2 Up (UM)");
        Berths.createOrGetBerth("CC0196");
        Berths.createOrGetBerth("CC0197").setName("MNG Plat 3 (DM)");
        Berths.createOrGetBerth("CC0198");
        Berths.createOrGetBerth("CC0199").setName("MNG Plat 2 Dn (UM)");
        Berths.createOrGetBerth("CC0201").setName("MNG Plat 1");
        Berths.createOrGetBerth("CC0203");
        Berths.createOrGetBerth("CC0205");
        Berths.createOrGetBerth("CC0207");
        Berths.createOrGetBerth("CC0209");
        Berths.createOrGetBerth("CC0211");
        Berths.createOrGetBerth("CC0228");
        Berths.createOrGetBerth("CC0229");
        Berths.createOrGetBerth("CC0230");
        Berths.createOrGetBerth("CC0231");
        Berths.createOrGetBerth("CC0232");
        Berths.createOrGetBerth("CC0233");
        Berths.createOrGetBerth("CC0234");
        Berths.createOrGetBerth("CC0268");
        Berths.createOrGetBerth("CC0269");
        Berths.createOrGetBerth("CC0270");
        Berths.createOrGetBerth("CC0271");
        Berths.createOrGetBerth("CC0272");
        Berths.createOrGetBerth("CC0273");
        Berths.createOrGetBerth("CC0274");
        Berths.createOrGetBerth("CC0275");
        Berths.createOrGetBerth("CC0276");
        Berths.createOrGetBerth("CC0277");
        Berths.createOrGetBerth("CC0278");
        Berths.createOrGetBerth("CC0279");
        Berths.createOrGetBerth("CC0280");
        Berths.createOrGetBerth("CC0281");
        Berths.createOrGetBerth("CC0282");
        Berths.createOrGetBerth("CC0283");
        Berths.createOrGetBerth("CC0284");
        Berths.createOrGetBerth("CC0285");
        Berths.createOrGetBerth("CC0286");
        Berths.createOrGetBerth("CC0753");
        Berths.createOrGetBerth("CC0766");
        Berths.createOrGetBerth("CCAPIP");
        Berths.createOrGetBerth("CCAPPA");
        Berths.createOrGetBerth("CCP001");
        Berths.createOrGetBerth("CCP002");
        Berths.createOrGetBerth("CCP003");
        Berths.createOrGetBerth("CCP004");
        Berths.createOrGetBerth("CCP005");
        Berths.createOrGetBerth("CCP006");
        Berths.createOrGetBerth("CCP007");
        Berths.createOrGetBerth("CCP008");
        Berths.createOrGetBerth("CCP009");
        Berths.createOrGetBerth("CCP010");
        Berths.createOrGetBerth("CCP012");
        Berths.createOrGetBerth("CCP014");
        Berths.createOrGetBerth("CCP021");
        Berths.createOrGetBerth("CCP022").setName("HPQ Plat 1");
        Berths.createOrGetBerth("CCP024");
        Berths.createOrGetBerth("CCP026").setName("HPQ Plat 2 Up (U&DH)");
        Berths.createOrGetBerth("CCP028").setName("HPQ Plat 3");
        Berths.createOrGetBerth("CCP037").setName("HPQ Plat 1 Dn");
        Berths.createOrGetBerth("CCP039").setName("HPQ Plat 2 Dn (U&DH)");
        Berths.createOrGetBerth("CCP050");
        Berths.createOrGetBerth("CCP057");
        Berths.createOrGetBerth("CCP058");
        Berths.createOrGetBerth("CCP065");
        Berths.createOrGetBerth("CCP074").setName("HWC Plat 1 (U&DH)");
        Berths.createOrGetBerth("CCPKSD");
        Berths.createOrGetBerth("CCPKTP");
        Berths.createOrGetBerth("CCR201").setName("MNG Plat 1");

        Berths.createOrGetBerth("CC0177");
        Berths.createOrGetBerth("CC0178");
        Berths.createOrGetBerth("CC0179");
        Berths.createOrGetBerth("CC0180");
        Berths.createOrGetBerth("CC0181");
        Berths.createOrGetBerth("CC0182");
        Berths.createOrGetBerth("CC0183");
        Berths.createOrGetBerth("CC0184");
        Berths.createOrGetBerth("CC0185");
        Berths.createOrGetBerth("CC0186");
        Berths.createOrGetBerth("CC0187");
        Berths.createOrGetBerth("CC0188");
        Berths.createOrGetBerth("CC0189");
        Berths.createOrGetBerth("CC1004").addStepToBerth("CC1004", "SE0882", "CCL882", "suggest");
        Berths.createOrGetBerth("CC1005");
        Berths.createOrGetBerth("CC1006");
        Berths.createOrGetBerth("CC1007");
        Berths.createOrGetBerth("CC1008");
        Berths.createOrGetBerth("CC1009");
        Berths.createOrGetBerth("CC1010");
        Berths.createOrGetBerth("CC1011");
        Berths.createOrGetBerth("CC1020");
        Berths.createOrGetBerth("CC1021");
        Berths.createOrGetBerth("CC1022");
        Berths.createOrGetBerth("CC1023");
        Berths.createOrGetBerth("CC1027");
        Berths.createOrGetBerth("CC1028");
        Berths.createOrGetBerth("CC1030");
        Berths.createOrGetBerth("CC1033");
        Berths.createOrGetBerth("CC1034");
        Berths.createOrGetBerth("CC1035");
        Berths.createOrGetBerth("CC1036");
        Berths.createOrGetBerth("CC1039");
        Berths.createOrGetBerth("CC1040").setName("COL Plat 3 Up (UM)");
        Berths.createOrGetBerth("CC1046");
        Berths.createOrGetBerth("CC1047");
        Berths.createOrGetBerth("CC1048").setName("COL Plat 6");
        Berths.createOrGetBerth("CC1051");
        Berths.createOrGetBerth("CC1054").setName("COL Plat 1 Up (DPL)");
        Berths.createOrGetBerth("CC1055");
        Berths.createOrGetBerth("CC1056").setName("COL Plat 2 Up (DM)");
        Berths.createOrGetBerth("CC1057");
        Berths.createOrGetBerth("CC1058").setName("COL Plat 4 Up");
        Berths.createOrGetBerth("CC1059");
        Berths.createOrGetBerth("CC1063").setName("COL Plat 3 Dn (UM)");
        Berths.createOrGetBerth("CC1065").setName("COL Plat 1 Dn (DPL)");
        Berths.createOrGetBerth("CC1067").setName("COL Plat 2 Dn (DM)");
        Berths.createOrGetBerth("CC1069").setName("COL Plat 4 Dn");
        Berths.createOrGetBerth("CC1071").setName("COL Plat 5");
        Berths.createOrGetBerth("CC1072");
        Berths.createOrGetBerth("CC1073");
        Berths.createOrGetBerth("CC1074");
        Berths.createOrGetBerth("CC1075");
        Berths.createOrGetBerth("CC1076");
        Berths.createOrGetBerth("CC1080");
        Berths.createOrGetBerth("CC1083");
        Berths.createOrGetBerth("CC1085");
        Berths.createOrGetBerth("CC4006");
        Berths.createOrGetBerth("CC4009");
        Berths.createOrGetBerth("CC4010");
        Berths.createOrGetBerth("CC4013");
        Berths.createOrGetBerth("CCAPDM");
        Berths.createOrGetBerth("CCAPUM");
        Berths.createOrGetBerth("CCP5AR");
        Berths.createOrGetBerth("CCP6AR");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Harlow">
    private static void initHarlow()
    {
        Berths.createOrGetBerth("WG1061");
        Berths.createOrGetBerth("WG1062");
        Berths.createOrGetBerth("WG1063");
        Berths.createOrGetBerth("WG1064");
        Berths.createOrGetBerth("WG1065");
        Berths.createOrGetBerth("WG1066");
        Berths.createOrGetBerth("WG1067");
        Berths.createOrGetBerth("WG1068");
        Berths.createOrGetBerth("WG1069");
        Berths.createOrGetBerth("WG1070");
        Berths.createOrGetBerth("WG1071");
        Berths.createOrGetBerth("WG1072");
        Berths.createOrGetBerth("WG1073");
        Berths.createOrGetBerth("WG1074");
        Berths.createOrGetBerth("WG1077");
        Berths.createOrGetBerth("WG1080");
        Berths.createOrGetBerth("WG1081");
        Berths.createOrGetBerth("WG1083");
        Berths.createOrGetBerth("WG1085");
        Berths.createOrGetBerth("WG1086");
        Berths.createOrGetBerth("WG1088");
        Berths.createOrGetBerth("WG1089");
        Berths.createOrGetBerth("WG1090");
        Berths.createOrGetBerth("WG1091");
        Berths.createOrGetBerth("WG1092");
        Berths.createOrGetBerth("WG1094");
        Berths.createOrGetBerth("WG1095");
        Berths.createOrGetBerth("WG1097");
        Berths.createOrGetBerth("WG1098");
        Berths.createOrGetBerth("WG1099");
        Berths.createOrGetBerth("WG1100");
        Berths.createOrGetBerth("WG1101");
        Berths.createOrGetBerth("WG1103");
        Berths.createOrGetBerth("WG1104");
        Berths.createOrGetBerth("WG1106");
        Berths.createOrGetBerth("WG1108");
        Berths.createOrGetBerth("WG1109");
        Berths.createOrGetBerth("WG1110");
        Berths.createOrGetBerth("WG1111");
        Berths.createOrGetBerth("WG1115");
        Berths.createOrGetBerth("WG1116");
        Berths.createOrGetBerth("WG1118");
        Berths.createOrGetBerth("WG1121");
        Berths.createOrGetBerth("WG1122");
        Berths.createOrGetBerth("WG1224");
        Berths.createOrGetBerth("WG1226");
        Berths.createOrGetBerth("WG1455");
        Berths.createOrGetBerth("WG1459");
        Berths.createOrGetBerth("WG1461");
        Berths.createOrGetBerth("WG1463");
        Berths.createOrGetBerth("WG1465");
        Berths.createOrGetBerth("WG1494");
        Berths.createOrGetBerth("WG1480");
        Berths.createOrGetBerth("WG1484");
        Berths.createOrGetBerth("WG1490");
        Berths.createOrGetBerth("WG5315");
        Berths.createOrGetBerth("WG5319");
        Berths.createOrGetBerth("WG5321");
        Berths.createOrGetBerth("WG5322");
        Berths.createOrGetBerth("WG5325");
        Berths.createOrGetBerth("WG5327");
        Berths.createOrGetBerth("WG5328");
        Berths.createOrGetBerth("WG5329");
        Berths.createOrGetBerth("WG5331");
        Berths.createOrGetBerth("WG5342");
        Berths.createOrGetBerth("WGHMYD");
        Berths.createOrGetBerth("WGSDG1");
        Berths.createOrGetBerth("WGSDG2");

        Berths.createOrGetBerth("WG1123");
        Berths.createOrGetBerth("WG1125");
        Berths.createOrGetBerth("WG1126");
        Berths.createOrGetBerth("WG1128");
        Berths.createOrGetBerth("WG1129");
        Berths.createOrGetBerth("WG1130");
        Berths.createOrGetBerth("WG1131");
        Berths.createOrGetBerth("WG1133");
        Berths.createOrGetBerth("WG1134");
        Berths.createOrGetBerth("WG1135");
        Berths.createOrGetBerth("WG1136");
        Berths.createOrGetBerth("WG1139");
        Berths.createOrGetBerth("WG1138");
        Berths.createOrGetBerth("WG1140");
        Berths.createOrGetBerth("WG1142");
        Berths.createOrGetBerth("WG1145");
        Berths.createOrGetBerth("WG1147");
        Berths.createOrGetBerth("WG1148");
        Berths.createOrGetBerth("WG1150");
        Berths.createOrGetBerth("WG1151");
        Berths.createOrGetBerth("WG1153");
        Berths.createOrGetBerth("WG1154");
        Berths.createOrGetBerth("WG1155");
        Berths.createOrGetBerth("WG1157");
        Berths.createOrGetBerth("WG1163");
        Berths.createOrGetBerth("WG1165");
        Berths.createOrGetBerth("WG1167");
        Berths.createOrGetBerth("WG1168");
        Berths.createOrGetBerth("WG1169");
        Berths.createOrGetBerth("WG1173");
        Berths.createOrGetBerth("WG1175");
        Berths.createOrGetBerth("WG1183").addStepToBerth("WG1183", "CA0019", "WG1187", "suggest");
        Berths.createOrGetBerth("WG1187");
        Berths.createOrGetBerth("WG1158");
        Berths.createOrGetBerth("WG1160");
        Berths.createOrGetBerth("WG1162");
        Berths.createOrGetBerth("WG1170");
        Berths.createOrGetBerth("WG1172");
        Berths.createOrGetBerth("WG1174");
        Berths.createOrGetBerth("WG1176");
        Berths.createOrGetBerth("WG1178");
        Berths.createOrGetBerth("WG1184");
        Berths.createOrGetBerth("WG1186");
        Berths.createOrGetBerth("WG1188");
        Berths.createOrGetBerth("WG1281");
        Berths.createOrGetBerth("WG1284");
        Berths.createOrGetBerth("WG1492");
        Berths.createOrGetBerth("WG1493");
        Berths.createOrGetBerth("WG1496");
        Berths.createOrGetBerth("WG1497");
        Berths.createOrGetBerth("WG1498");
        Berths.createOrGetBerth("WG5383");
        Berths.createOrGetBerth("WG5385");
        Berths.createOrGetBerth("WG5387");
        Berths.createOrGetBerth("WG5396");
        Berths.createOrGetBerth("WG5397");
        Berths.createOrGetBerth("WGGF03");
        Berths.createOrGetBerth("WGUPSD");

        Berths.createOrGetBerth("WG1230");
        Berths.createOrGetBerth("WG1231");
        Berths.createOrGetBerth("WG1232");
        Berths.createOrGetBerth("WG1233");
        Berths.createOrGetBerth("WG1234");
        Berths.createOrGetBerth("WG1236");
        Berths.createOrGetBerth("WG1237");
        Berths.createOrGetBerth("WG1238");
        Berths.createOrGetBerth("WG1239");
        Berths.createOrGetBerth("WG1240");
        Berths.createOrGetBerth("WG1241");
        Berths.createOrGetBerth("WG1242");
        Berths.createOrGetBerth("WG1243");
        Berths.createOrGetBerth("WG1244");
        Berths.createOrGetBerth("WG1245");
        Berths.createOrGetBerth("WG1246");
        Berths.createOrGetBerth("WG1247");
        Berths.createOrGetBerth("WG1252");
        Berths.createOrGetBerth("WG1253");
        Berths.createOrGetBerth("WG1254");
        Berths.createOrGetBerth("WG1255");
        Berths.createOrGetBerth("WG1256");
        Berths.createOrGetBerth("WG1257");
        Berths.createOrGetBerth("WGA262");
        Berths.createOrGetBerth("WGA264");
        Berths.createOrGetBerth("WGB262");
        Berths.createOrGetBerth("WGB264");
        Berths.createOrGetBerth("WGR262");
        Berths.createOrGetBerth("WGR264");

        Berths.createOrGetBerth("WG1143");
        Berths.createOrGetBerth("WG1192");
        Berths.createOrGetBerth("WG1193");
        Berths.createOrGetBerth("WG1194");
        Berths.createOrGetBerth("WG1196");
        Berths.createOrGetBerth("WG1197");
        Berths.createOrGetBerth("WG1198");
        Berths.createOrGetBerth("WG1199");
        Berths.createOrGetBerth("WG1201");
        Berths.createOrGetBerth("WG1202");
        Berths.createOrGetBerth("WG1213").addStepToBerth("WG1213", "CA0019", "WG1187", "suggest");
        Berths.createOrGetBerth("WG1220");
        Berths.createOrGetBerth("WG1366");
        Berths.createOrGetBerth("WGA168");
        Berths.createOrGetBerth("WGA206");
        Berths.createOrGetBerth("WGA370");
        Berths.createOrGetBerth("WGB168");
        Berths.createOrGetBerth("WGB206");
        Berths.createOrGetBerth("WGB370");
        Berths.createOrGetBerth("WGC168");
        Berths.createOrGetBerth("WGC206");
        Berths.createOrGetBerth("WGC370");
        Berths.createOrGetBerth("WGR168");
        Berths.createOrGetBerth("WGR206");
        Berths.createOrGetBerth("WGR370");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Hackney">
    private static void initHackney()
    {
        //Cambs heath - Clapton Jnc
        Berths.createOrGetBerth("LS0120");
        Berths.createOrGetBerth("LS0121");
        Berths.createOrGetBerth("LS0122");
        Berths.createOrGetBerth("LS0123");
        Berths.createOrGetBerth("LS0124");
        Berths.createOrGetBerth("LS0125");
        Berths.createOrGetBerth("LS0126");
        Berths.createOrGetBerth("LS0127");
        Berths.createOrGetBerth("LS0128");
        Berths.createOrGetBerth("LS1271");
        Berths.createOrGetBerth("LS0129");
        Berths.createOrGetBerth("LS0130");
        Berths.createOrGetBerth("LS0131");
        Berths.createOrGetBerth("LS0132");
        Berths.createOrGetBerth("LS0134");
        Berths.createOrGetBerth("LS0135");
        Berths.createOrGetBerth("LS0136");
        Berths.createOrGetBerth("LS0137");
        Berths.createOrGetBerth("LS0139");
        Berths.createOrGetBerth("LS0140");
        Berths.createOrGetBerth("LS0141");
        Berths.createOrGetBerth("LS0142");
        Berths.createOrGetBerth("LS0145");
        Berths.createOrGetBerth("LS0147");
        Berths.createOrGetBerth("LS0156");
        Berths.createOrGetBerth("LS0157");
        Berths.createOrGetBerth("LS0158");
        Berths.createOrGetBerth("LS0159");
        Berths.createOrGetBerth("LS0160");
        Berths.createOrGetBerth("LS0161");
        Berths.createOrGetBerth("LS0162");
        Berths.createOrGetBerth("LS0164");
        Berths.createOrGetBerth("LS0165");
        Berths.createOrGetBerth("LS0166");
        Berths.createOrGetBerth("LS0167").addStepToBerth("LS0167", "WG1007", "cancel", "suggest");
        Berths.createOrGetBerth("LS0170");
        Berths.createOrGetBerth("LS1302");
        Berths.createOrGetBerth("LS1303");
        Berths.createOrGetBerth("LS1304");
        Berths.createOrGetBerth("LS1305").addStepToBerth("LS1305", "WG1307", "cancel", "suggest");
        Berths.createOrGetBerth("LS1404");
        Berths.createOrGetBerth("LS1405");
        Berths.createOrGetBerth("LS1407");

        //Clpton Jnc - Chingford
        Berths.createOrGetBerth("LS1408");
        Berths.createOrGetBerth("LS1410");
        Berths.createOrGetBerth("LS1411");
        Berths.createOrGetBerth("LS1412");
        Berths.createOrGetBerth("LS1413");
        Berths.createOrGetBerth("LS1414");
        Berths.createOrGetBerth("LS1415");
        Berths.createOrGetBerth("LS1418");
        Berths.createOrGetBerth("LS1419");
        Berths.createOrGetBerth("LS1420");
        Berths.createOrGetBerth("LS1421");
        Berths.createOrGetBerth("LS1422");
        Berths.createOrGetBerth("LS1423");
        Berths.createOrGetBerth("LS1424");
        Berths.createOrGetBerth("LS1425");
        Berths.createOrGetBerth("LS1427");
        Berths.createOrGetBerth("LS1428");
        Berths.createOrGetBerth("LS1429");
        Berths.createOrGetBerth("LS1430");
        Berths.createOrGetBerth("LS1431");
        Berths.createOrGetBerth("LS1433");
        Berths.createOrGetBerth("LS1432");
        Berths.createOrGetBerth("LS1434");
        Berths.createOrGetBerth("LS1438");
        Berths.createOrGetBerth("LS1440");
        Berths.createOrGetBerth("LS1442");
        Berths.createOrGetBerth("LS5557");
        Berths.createOrGetBerth("LS5561");
        Berths.createOrGetBerth("LSA444");
        Berths.createOrGetBerth("LSA446");
        Berths.createOrGetBerth("LSA448");
        Berths.createOrGetBerth("LSB444");
        Berths.createOrGetBerth("LSB446");
        Berths.createOrGetBerth("LSB448");
        Berths.createOrGetBerth("LSR444");
        Berths.createOrGetBerth("LSR446");
        Berths.createOrGetBerth("LSR448");
        Berths.createOrGetBerth("LSCHAC");
        Berths.createOrGetBerth("LSCHAL");

        //Hackney - Bury St Jnc
        Berths.createOrGetBerth("WG1306").addStepToBerth("WG1306", "LS1304", "cancel", "suggest");
        Berths.createOrGetBerth("WG1307");
        Berths.createOrGetBerth("WG1308");
        Berths.createOrGetBerth("WG1310");
        Berths.createOrGetBerth("WG1311");
        Berths.createOrGetBerth("WG1312");
        Berths.createOrGetBerth("WG1315");
        Berths.createOrGetBerth("WG1316");
        Berths.createOrGetBerth("WG1317");
        Berths.createOrGetBerth("WG1318");
        Berths.createOrGetBerth("WG1319");
        Berths.createOrGetBerth("WG1320");
        Berths.createOrGetBerth("WG1321");
        Berths.createOrGetBerth("WG1324");
        Berths.createOrGetBerth("WG1325");
        Berths.createOrGetBerth("WG1326");
        Berths.createOrGetBerth("WG1327");
        Berths.createOrGetBerth("WG1329");
        Berths.createOrGetBerth("WG1330");
        Berths.createOrGetBerth("WG1331");
        Berths.createOrGetBerth("WG1332");
        Berths.createOrGetBerth("WG1333");
        Berths.createOrGetBerth("WG1334");
        Berths.createOrGetBerth("WG1336");
        Berths.createOrGetBerth("WG1337");
        Berths.createOrGetBerth("WG1338");
        Berths.createOrGetBerth("WG1339");
        Berths.createOrGetBerth("WG1340");
        Berths.createOrGetBerth("WG1341");
        Berths.createOrGetBerth("WG1342");
        Berths.createOrGetBerth("WG1344");
        Berths.createOrGetBerth("WG1345");
        Berths.createOrGetBerth("WG1346");
        Berths.createOrGetBerth("WG1347");
        Berths.createOrGetBerth("WG1348");
        Berths.createOrGetBerth("WG1349");
        Berths.createOrGetBerth("WG1351");
        Berths.createOrGetBerth("WG1353");
        Berths.createOrGetBerth("WG1368");
        Berths.createOrGetBerth("WG1371");
        Berths.createOrGetBerth("WG1372");
        Berths.createOrGetBerth("WG1373");
        Berths.createOrGetBerth("WG1375");

        //Bury St Jnc - Enfield Town
        Berths.createOrGetBerth("WG1350");
        Berths.createOrGetBerth("WG1352");
        Berths.createOrGetBerth("WG1356");
        Berths.createOrGetBerth("WGA360");
        Berths.createOrGetBerth("WGA362");
        Berths.createOrGetBerth("WGA364");
        Berths.createOrGetBerth("WGB360");
        Berths.createOrGetBerth("WGB362");
        Berths.createOrGetBerth("WGB364");
        Berths.createOrGetBerth("WGR360");
        Berths.createOrGetBerth("WGR362");
        Berths.createOrGetBerth("WGR364");
        Berths.createOrGetBerth("WG1361");
        Berths.createOrGetBerth("WG1363");
        Berths.createOrGetBerth("WG1365");

        //Temple Mills/Southbury - Cheshunt
        Berths.createOrGetBerth("WG1003");
        Berths.createOrGetBerth("WG1005");
        Berths.createOrGetBerth("WG1004");
        Berths.createOrGetBerth("WG1007");
        Berths.createOrGetBerth("WG1009");
        Berths.createOrGetBerth("WG1010").addStepToBerth("WG1010", "LS0170", "cancel", "suggest").addStepToBerth("WG1010", "SIS718", "cancel", "suggest");
        Berths.createOrGetBerth("WG1011");
        Berths.createOrGetBerth("WG1012");
        Berths.createOrGetBerth("WG1013");
        Berths.createOrGetBerth("WG1014");
        Berths.createOrGetBerth("WG1015");
        Berths.createOrGetBerth("WG1016");
        Berths.createOrGetBerth("WG1017");
        Berths.createOrGetBerth("WG1018");
        Berths.createOrGetBerth("WG1020");
        Berths.createOrGetBerth("WG1021");
        Berths.createOrGetBerth("WG1022");
        Berths.createOrGetBerth("WG1023");
        Berths.createOrGetBerth("WG1025");
        Berths.createOrGetBerth("WG1026");
        Berths.createOrGetBerth("WG1027");
        Berths.createOrGetBerth("WG1028");
        Berths.createOrGetBerth("WG1029");
        Berths.createOrGetBerth("WG1030");
        Berths.createOrGetBerth("WG1031");
        Berths.createOrGetBerth("WG1033");
        Berths.createOrGetBerth("WG1034");
        Berths.createOrGetBerth("WG1036");
        Berths.createOrGetBerth("WG1037");
        Berths.createOrGetBerth("WG1038");
        Berths.createOrGetBerth("WG1039");
        Berths.createOrGetBerth("WG1040");
        Berths.createOrGetBerth("WG1041");
        Berths.createOrGetBerth("WG1042");
        Berths.createOrGetBerth("WG1044");
        Berths.createOrGetBerth("WG1045");
        Berths.createOrGetBerth("WG1046");
        Berths.createOrGetBerth("WG1047");
        Berths.createOrGetBerth("WG1049");
        Berths.createOrGetBerth("WG1050");
        Berths.createOrGetBerth("WG1052");
        Berths.createOrGetBerth("WG1053");
        Berths.createOrGetBerth("WG1054");
        Berths.createOrGetBerth("WG1055");
        Berths.createOrGetBerth("WG1056");
        Berths.createOrGetBerth("WG1057");
        Berths.createOrGetBerth("WG1058");
        Berths.createOrGetBerth("WG1059");
        Berths.createOrGetBerth("WG1060");
        Berths.createOrGetBerth("WG1144");
        Berths.createOrGetBerth("WG1374");
        Berths.createOrGetBerth("WG1376");
        Berths.createOrGetBerth("WG1377");
        Berths.createOrGetBerth("WG1378");
        Berths.createOrGetBerth("WG1379");
        Berths.createOrGetBerth("WG1380");
        Berths.createOrGetBerth("WG1381");
        Berths.createOrGetBerth("WG1382");
        Berths.createOrGetBerth("WG1383");
        Berths.createOrGetBerth("WG1384");
        Berths.createOrGetBerth("WG1385");
        Berths.createOrGetBerth("WG1386");
        Berths.createOrGetBerth("WG1387");
        Berths.createOrGetBerth("WG1388");
        Berths.createOrGetBerth("WG1389");
        Berths.createOrGetBerth("WG1390");
        Berths.createOrGetBerth("WG1391");
        Berths.createOrGetBerth("WG1392");
        Berths.createOrGetBerth("WG1393");
        Berths.createOrGetBerth("WG1394");
        Berths.createOrGetBerth("WG1395");
        Berths.createOrGetBerth("WGR144");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Witham">
    private static void initWitham()
    {
        Berths.createOrGetBerth("SE0669");
        Berths.createOrGetBerth("SE0671");
        Berths.createOrGetBerth("SE0675");
        Berths.createOrGetBerth("SE0677");
        Berths.createOrGetBerth("SE0679");
        Berths.createOrGetBerth("SE0683").setName("INT Plat 2 Dn (DM)");
        Berths.createOrGetBerth("SE0685");
        Berths.createOrGetBerth("SE0687");
        Berths.createOrGetBerth("SE0691");
        Berths.createOrGetBerth("SE0693");
        Berths.createOrGetBerth("SE0695");
        Berths.createOrGetBerth("SE0697");
        Berths.createOrGetBerth("SE0701");
        Berths.createOrGetBerth("SE0703");
        Berths.createOrGetBerth("SE0705");
        Berths.createOrGetBerth("SE0710");
        Berths.createOrGetBerth("SE0711");
        Berths.createOrGetBerth("SE0712").setName("INT Plat 2 Up (DM)");
        Berths.createOrGetBerth("SE0713");
        Berths.createOrGetBerth("SE0714").setName("INT Plat 1 (UM)");
        Berths.createOrGetBerth("SE0715").setName("CHM Plat 2 Dn (DM)");
        Berths.createOrGetBerth("SE0716");
        Berths.createOrGetBerth("SE0717").setName("CHM Plat 1 Up (UM)");
        Berths.createOrGetBerth("SE0718");
        Berths.createOrGetBerth("SE0722");
        Berths.createOrGetBerth("SE0723");
        Berths.createOrGetBerth("SE0724");
        Berths.createOrGetBerth("SE0725");
        Berths.createOrGetBerth("SE0726");
        Berths.createOrGetBerth("SE0727");
        Berths.createOrGetBerth("SE0729");
        Berths.createOrGetBerth("SE0730");
        Berths.createOrGetBerth("SE0732");
        Berths.createOrGetBerth("SE0734");
        Berths.createOrGetBerth("SE0736");
        Berths.createOrGetBerth("SE0740");
        Berths.createOrGetBerth("SE0742");
        Berths.createOrGetBerth("SE0756");
        Berths.createOrGetBerth("SE0758").setName("CHM Plat 2 Up (DM)");
        Berths.createOrGetBerth("SE0760").setName("CHM Plat 1 Dn (UM)");
        Berths.createOrGetBerth("SE0762");
        Berths.createOrGetBerth("SE0764");
        Berths.createOrGetBerth("SE0766");
        Berths.createOrGetBerth("SE0770");
        Berths.createOrGetBerth("SE0772");

        Berths.createOrGetBerth("SE0731");
        Berths.createOrGetBerth("SE0733");
        Berths.createOrGetBerth("SE0735");
        Berths.createOrGetBerth("SE0737");
        Berths.createOrGetBerth("SE0739");
        Berths.createOrGetBerth("SE0741");
        Berths.createOrGetBerth("SE0747");
        Berths.createOrGetBerth("SE0751").setName("HAP Plat 2 Dn (DM)");
        Berths.createOrGetBerth("SE0753").setName("HAP Plat 1 Dn (UM)");
        Berths.createOrGetBerth("SE0755");
        Berths.createOrGetBerth("SE0759");
        Berths.createOrGetBerth("SE0761");
        Berths.createOrGetBerth("SE0763");
        Berths.createOrGetBerth("SE0765").setName("WTM Plat 4 Dn (DPL)");
        Berths.createOrGetBerth("SE0769");
        Berths.createOrGetBerth("SE0767");
        Berths.createOrGetBerth("SE0769").setName("WTM Plat 3 Dn (DM)");
        Berths.createOrGetBerth("SE0771").setName("WTM Plat 2 Dn (UM)");
        Berths.createOrGetBerth("SE0773").setName("WTM Plat 1 Dn (UPL)");
        Berths.createOrGetBerth("SE0778");
        Berths.createOrGetBerth("SE0779");
        Berths.createOrGetBerth("SE0781");
        Berths.createOrGetBerth("SE0782");
        Berths.createOrGetBerth("SE0784");
        Berths.createOrGetBerth("SE0785");
        Berths.createOrGetBerth("SE0786");
        Berths.createOrGetBerth("SE0787");
        Berths.createOrGetBerth("SE0788");
        Berths.createOrGetBerth("SE0789");
        Berths.createOrGetBerth("SE0790");
        Berths.createOrGetBerth("SE0791");
        Berths.createOrGetBerth("SE0792");
        Berths.createOrGetBerth("SE0793");
        Berths.createOrGetBerth("SE0794").setName("HAP Plat 2 Up (DM)");
        Berths.createOrGetBerth("SE0796").setName("HAP Plat 1 Up (UM)");
        Berths.createOrGetBerth("SE0799").setName("KEL Plat 2 Dn (DM)");
        Berths.createOrGetBerth("SE0800");
        Berths.createOrGetBerth("SE0801");
        Berths.createOrGetBerth("SE0803");
        Berths.createOrGetBerth("SE0804");
        Berths.createOrGetBerth("SE0805");
        Berths.createOrGetBerth("SE0806");
        Berths.createOrGetBerth("SE0807");
        Berths.createOrGetBerth("SE0810").setName("WTM Plat 4 Up (DPL)");
        Berths.createOrGetBerth("SE0812").setName("WTM Plat 3 Up (DM)");
        Berths.createOrGetBerth("SE0814").setName("WTM Plat 2 Up (UM)");
        Berths.createOrGetBerth("SE0815");
        Berths.createOrGetBerth("SE0816").setName("WTM Plat 1 Up (UPL)");
        Berths.createOrGetBerth("SE0819");
        Berths.createOrGetBerth("SE0817");
        Berths.createOrGetBerth("SE0818");
        Berths.createOrGetBerth("SE0820");
        Berths.createOrGetBerth("SE0822");
        Berths.createOrGetBerth("SE0823");
        Berths.createOrGetBerth("SE0824");
        Berths.createOrGetBerth("SE0825").setName("MKT Plat 3 Dn (U&DS)");
        Berths.createOrGetBerth("SE0826");
        Berths.createOrGetBerth("SE0827").setName("MKT Plat 2 Dn (DM)");
        Berths.createOrGetBerth("SE0828");
        Berths.createOrGetBerth("SE0829").setName("MKT Plat 1 Dn (UM)");
        Berths.createOrGetBerth("SE0830");
        Berths.createOrGetBerth("SE0832");
        Berths.createOrGetBerth("SE0834");
        Berths.createOrGetBerth("SE0836");
        Berths.createOrGetBerth("SE0837").addStepToBerth("SE0837", "CC1005", "SE1005", "suggest");
        Berths.createOrGetBerth("SE0839");
        Berths.createOrGetBerth("SE0844").setName("KEL Plat 2 Up (DM)");
        Berths.createOrGetBerth("SE0846").setName("KEL Plat 1 (UM)");
        Berths.createOrGetBerth("SE0848");
        Berths.createOrGetBerth("SE0850");
        Berths.createOrGetBerth("SE0854");
        Berths.createOrGetBerth("SE0856");
        Berths.createOrGetBerth("SE0858");
        Berths.createOrGetBerth("SE0860");
        Berths.createOrGetBerth("SE0862").setName("MKT Plat 2 Up (DM)");
        Berths.createOrGetBerth("SE0864").setName("MKT Plat 1 Up (UM)");
        Berths.createOrGetBerth("SE0868").setName("MKT Plat 3 Up (U&DS)");
        Berths.createOrGetBerth("SE0874");
        Berths.createOrGetBerth("SE0876");
        Berths.createOrGetBerth("SE0878");
        Berths.createOrGetBerth("SE0882");
        Berths.createOrGetBerth("SE0884");
        Berths.createOrGetBerth("SE0896");
        Berths.createOrGetBerth("SE0898");
        Berths.createOrGetBerth("SE5202");
        Berths.createOrGetBerth("SE5203");
        Berths.createOrGetBerth("SECRES");
        Berths.createOrGetBerth("SEDEPO");
        Berths.createOrGetBerth("SER896");
        Berths.createOrGetBerth("SER898");
        Berths.createOrGetBerth("SESHAL");
        Berths.createOrGetBerth("SEUSDG");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Shenfield">
    private static void initShenfield()
    {
        Berths.createOrGetBerth("SE0445");
        Berths.createOrGetBerth("SE0447").setName("HRO Plat 4 (DE)");
        Berths.createOrGetBerth("SE0449").setName("HRO Plat 2 (DM)");
        Berths.createOrGetBerth("SE0451");
        Berths.createOrGetBerth("SE0453");
        Berths.createOrGetBerth("SE0455");
        Berths.createOrGetBerth("SE0457");
        Berths.createOrGetBerth("SE0459");
        Berths.createOrGetBerth("SE0461");
        Berths.createOrGetBerth("SE0463");
        Berths.createOrGetBerth("SE0465");
        Berths.createOrGetBerth("SE0467");
        Berths.createOrGetBerth("SE0469");
        Berths.createOrGetBerth("SE0471");
        Berths.createOrGetBerth("SE0473");
        Berths.createOrGetBerth("SE0475").setName("BRE Plat 4 (DE)");
        Berths.createOrGetBerth("SE0477").setName("BRE Plat 2 (DM)");
        Berths.createOrGetBerth("SE0478").addStepToBerth("SE0478", "SI0474", "SE0474", "suggest").setName("HRO Plat 3 (UE)");
        Berths.createOrGetBerth("SE0479");
        Berths.createOrGetBerth("SE0480").addStepToBerth("SE0480", "SI0476", "cancel", "suggest").setName("HRO Plat 1 (UM)");
        Berths.createOrGetBerth("SE0481");
        Berths.createOrGetBerth("SE0482");
        Berths.createOrGetBerth("SE0483");
        Berths.createOrGetBerth("SE0484");
        Berths.createOrGetBerth("SE0485");
        Berths.createOrGetBerth("SE0487");
        Berths.createOrGetBerth("SE0489");
        Berths.createOrGetBerth("SE0486");
        Berths.createOrGetBerth("SE0488");
        Berths.createOrGetBerth("SE0490");
        Berths.createOrGetBerth("SE0491");
        Berths.createOrGetBerth("SE0492");
        Berths.createOrGetBerth("SE0493");
        Berths.createOrGetBerth("SE0494");
        Berths.createOrGetBerth("SE0495").setName("SNF Plat 5 Dn (DE)");
        Berths.createOrGetBerth("SE0496");
        Berths.createOrGetBerth("SE0497").setName("SNF Plat 4 Dn (UE)");
        Berths.createOrGetBerth("SE0498").setName("BRE Plat 3 (UE)");
        Berths.createOrGetBerth("SE0499").setName("SNF Plat 3 Dn (DM)");
        Berths.createOrGetBerth("SE0500").setName("BRE Plat 1 (UM)");
        Berths.createOrGetBerth("SE0501").setName("SNF Plat 2 Dn (UM)");
        Berths.createOrGetBerth("SE0502");
        Berths.createOrGetBerth("SE0503").setName("SNF Plat 1 Dn (USD)");
        Berths.createOrGetBerth("SE0504");
        Berths.createOrGetBerth("SE0505");
        Berths.createOrGetBerth("SE0506");
        Berths.createOrGetBerth("SE0507");
        Berths.createOrGetBerth("SE0508");
        Berths.createOrGetBerth("SE0509");
        Berths.createOrGetBerth("SE0510");
        Berths.createOrGetBerth("SE0511");
        Berths.createOrGetBerth("SE0512");
        Berths.createOrGetBerth("SE0513");
        Berths.createOrGetBerth("SE0514");
        Berths.createOrGetBerth("SE0515");
        Berths.createOrGetBerth("SE0516").setName("SNF Plat 5 Up (DE)");
        Berths.createOrGetBerth("SE0518").setName("SNF Plat 4 Up (UE)");
        Berths.createOrGetBerth("SE0522").setName("SNF Plat 2 Up (UM)");
        Berths.createOrGetBerth("SE0524").setName("SNF Plat 1 Up (USD)");
        Berths.createOrGetBerth("SE0528");
        Berths.createOrGetBerth("SE0530");
        Berths.createOrGetBerth("SE0534");
        Berths.createOrGetBerth("SE0536");
        Berths.createOrGetBerth("SE0538");
        Berths.createOrGetBerth("SE0540");
        Berths.createOrGetBerth("SE0542");
        Berths.createOrGetBerth("SE0544");
        Berths.createOrGetBerth("SE0552");
        Berths.createOrGetBerth("SE0554");
        Berths.createOrGetBerth("SE5132").setName("SNF Plat 3 Up (DM)");
        Berths.createOrGetBerth("SE5134");
        Berths.createOrGetBerth("SE5137");
        Berths.createOrGetBerth("SE5139");
        Berths.createOrGetBerth("SEA136");
        Berths.createOrGetBerth("SEA138");
        Berths.createOrGetBerth("SEDNSG");
        Berths.createOrGetBerth("SER136");
        Berths.createOrGetBerth("SER138");
        Berths.createOrGetBerth("SESMS1");
        Berths.createOrGetBerth("SESMS2");
        Berths.createOrGetBerth("SEUPSG");

        Berths.createOrGetBerth("SE0517");
        Berths.createOrGetBerth("SE0519");
        Berths.createOrGetBerth("SE0521");
        Berths.createOrGetBerth("SE0558");
        Berths.createOrGetBerth("SE0523");
        Berths.createOrGetBerth("SE0525");
        Berths.createOrGetBerth("SE0527");
        Berths.createOrGetBerth("SE0529");
        Berths.createOrGetBerth("SE0533").setName("BIC Plat 2 (DSD)");
        Berths.createOrGetBerth("SE0535").setName("BIC Plat 1 Dn (USD)");
        Berths.createOrGetBerth("SE0537");
        Berths.createOrGetBerth("SE0539");
        Berths.createOrGetBerth("SE0541");
        Berths.createOrGetBerth("SE0543");
        Berths.createOrGetBerth("SE0545");
        Berths.createOrGetBerth("SE0547");
        Berths.createOrGetBerth("SE0549");
        Berths.createOrGetBerth("SE0550");
        Berths.createOrGetBerth("SE0551");
        Berths.createOrGetBerth("SE0553").setName("WIC Plat 3 Dn (USD)");
        Berths.createOrGetBerth("SE0554").setName("WIC Plat 2 Up (DSD)");
        Berths.createOrGetBerth("SE0555").setName("WIC Plat 4");
        Berths.createOrGetBerth("SE0556");
        Berths.createOrGetBerth("SE0557").setName("WIC Plat 1");
        Berths.createOrGetBerth("SE0559").setName("WIC Plat 2 Dn (DSD)");
        Berths.createOrGetBerth("SE0560");
        Berths.createOrGetBerth("SE0562");
        Berths.createOrGetBerth("SE0564");
        Berths.createOrGetBerth("SE0566");
        Berths.createOrGetBerth("SE0568");
        Berths.createOrGetBerth("SE0569");
        Berths.createOrGetBerth("SE0570").setName("BIC Plat 1 Dn (USD)");
        Berths.createOrGetBerth("SE0571");
        Berths.createOrGetBerth("SE0572");
        Berths.createOrGetBerth("SE0573");
        Berths.createOrGetBerth("SE0574");
        Berths.createOrGetBerth("SE0575");
        Berths.createOrGetBerth("SE0576");
        Berths.createOrGetBerth("SE0577");
        Berths.createOrGetBerth("SE0578");
        Berths.createOrGetBerth("SE0579");
        Berths.createOrGetBerth("SE0580");
        Berths.createOrGetBerth("SE0581");
        Berths.createOrGetBerth("SE0582");
        Berths.createOrGetBerth("SE0584");
        Berths.createOrGetBerth("SE0586");
        Berths.createOrGetBerth("SE0588");
        Berths.createOrGetBerth("SE0592").setName("WIC Plat 3 Up (USD)");
        Berths.createOrGetBerth("SE0594");
        Berths.createOrGetBerth("SE0596");
        Berths.createOrGetBerth("SE0602");
        Berths.createOrGetBerth("SE0604");
        Berths.createOrGetBerth("SE0606");
        Berths.createOrGetBerth("SE0608");
        Berths.createOrGetBerth("SE0610");
        Berths.createOrGetBerth("SE0612");
        Berths.createOrGetBerth("SE0614");
        Berths.createOrGetBerth("SE0616");
        Berths.createOrGetBerth("SEWDNS");

        Berths.createOrGetBerth("SE0583").setName("RLG Plat 2 (DSD)");
        Berths.createOrGetBerth("SE0585");
        Berths.createOrGetBerth("SE0587");
        Berths.createOrGetBerth("SE0589");
        Berths.createOrGetBerth("SE0591");
        Berths.createOrGetBerth("SE0593");
        Berths.createOrGetBerth("SE0595");
        Berths.createOrGetBerth("SE0597").setName("HOC Plat 2 (DSD)");
        Berths.createOrGetBerth("SE0599").setName("HOC Plat 1 Dn (USD)");
        Berths.createOrGetBerth("SE0603");
        Berths.createOrGetBerth("SE0605");
        Berths.createOrGetBerth("SE0607");
        Berths.createOrGetBerth("SE0609");
        Berths.createOrGetBerth("SE0611").setName("RFD Plat 2 (DSD)");
        Berths.createOrGetBerth("SE0613").setName("RFD Plat 1 Dn (USD)");
        Berths.createOrGetBerth("SE0615");
        Berths.createOrGetBerth("SE0618").setName("RLG Plat 1 (USD)");
        Berths.createOrGetBerth("SE0619").setName("SIA Plat 2 Dn (DSD)");
        Berths.createOrGetBerth("SE0620");
        Berths.createOrGetBerth("SE0621");
        Berths.createOrGetBerth("SE0622");
        Berths.createOrGetBerth("SE0623");
        Berths.createOrGetBerth("SE0624");
        Berths.createOrGetBerth("SE0625").setName("PRL Plat 2 (DSD)");
        Berths.createOrGetBerth("SE0626");
        Berths.createOrGetBerth("SE0627").setName("PRL Plat 1 Dn (USD)");
        Berths.createOrGetBerth("SE0628");
        Berths.createOrGetBerth("SE0629");
        Berths.createOrGetBerth("SE0630");
        Berths.createOrGetBerth("SE0631");
        Berths.createOrGetBerth("SE0634").setName("HOC Plat 1 Up (USD)");
        Berths.createOrGetBerth("SE0636");
        Berths.createOrGetBerth("SE0638");
        Berths.createOrGetBerth("SE0639");
        Berths.createOrGetBerth("SE0640");
        Berths.createOrGetBerth("SE0642");
        Berths.createOrGetBerth("SE0644");
        Berths.createOrGetBerth("SE0646");
        Berths.createOrGetBerth("SE0648").setName("RFD Plat 1 Up (USD)");
        Berths.createOrGetBerth("SE0649");
        Berths.createOrGetBerth("SE0650");
        Berths.createOrGetBerth("SE0651");
        Berths.createOrGetBerth("SE0652").setName("SIA Plat 2 Up (DSD)");
        Berths.createOrGetBerth("SE0654").setName("SIA Plat 1 (USD)");
        Berths.createOrGetBerth("SE0658");
        Berths.createOrGetBerth("SE0660");
        Berths.createOrGetBerth("SE0662").setName("PRL Plat 1 Up (USD)");
        Berths.createOrGetBerth("SE0664");
        Berths.createOrGetBerth("SE0666");
        Berths.createOrGetBerth("SEA668").setName("SOV Plat 1a");
        Berths.createOrGetBerth("SEA670").setName("SOV Plat 2a");
        Berths.createOrGetBerth("SEA672").setName("SOV Plat 3a");
        Berths.createOrGetBerth("SEA674").setName("SOV Plat 4a");
        Berths.createOrGetBerth("SEB668").setName("SOV Plat 1b");
        Berths.createOrGetBerth("SEB670").setName("SOV Plat 2b");
        Berths.createOrGetBerth("SEB672").setName("SOV Plat 3b");
        Berths.createOrGetBerth("SEB674").setName("SOV Plat 4b");
        Berths.createOrGetBerth("SEC668").setName("SOV Plat 1c");
        Berths.createOrGetBerth("SEC670").setName("SOV Plat 2c");
        Berths.createOrGetBerth("SEC672").setName("SOV Plat 3c");
        Berths.createOrGetBerth("SEC674").setName("SOV Plat 4c");
        Berths.createOrGetBerth("SER668").setName("SOV Plat 1");
        Berths.createOrGetBerth("SER670").setName("SOV Plat 2");
        Berths.createOrGetBerth("SER672").setName("SOV Plat 3");
        Berths.createOrGetBerth("SER674").setName("SOV Plat 4");
        Berths.createOrGetBerth("SE0694");
        Berths.createOrGetBerth("SE0696");
        Berths.createOrGetBerth("SE0708");
        Berths.createOrGetBerth("SE5146");
        Berths.createOrGetBerth("SE5157");
        Berths.createOrGetBerth("SE5165");
        Berths.createOrGetBerth("SE5167");
        Berths.createOrGetBerth("SE5170");
        Berths.createOrGetBerth("SEBURN");
        Berths.createOrGetBerth("SEDNSS");
        Berths.createOrGetBerth("SEDNSN");
        Berths.createOrGetBerth("SER708");
        Berths.createOrGetBerth("SEUPSN");
        Berths.createOrGetBerth("SEUPSS");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Ilford">
    private static void initIlford()
    {
        Berths.createOrGetBerth("SI0383");
        Berths.createOrGetBerth("SI0385");
        Berths.createOrGetBerth("SI0387").setName("CTH Plat 4 (DE)");
        Berths.createOrGetBerth("SI0389").setName("CTH Plat 2 (DM)");
        Berths.createOrGetBerth("SI0391");
        Berths.createOrGetBerth("SI0393");
        Berths.createOrGetBerth("SI0395");
        Berths.createOrGetBerth("SI0397");
        Berths.createOrGetBerth("SI0399");
        Berths.createOrGetBerth("SI0401");
        Berths.createOrGetBerth("SI0403");
        Berths.createOrGetBerth("SI0405");
        Berths.createOrGetBerth("SI0407");
        Berths.createOrGetBerth("SI0409");
        Berths.createOrGetBerth("SI0410");
        Berths.createOrGetBerth("SI0411");
        Berths.createOrGetBerth("SI0412");
        Berths.createOrGetBerth("SI0413");
        Berths.createOrGetBerth("SI0414").setName("CTH Plat 3 (UE)");
        Berths.createOrGetBerth("SI0415");
        Berths.createOrGetBerth("SI0416").setName("CTH Plat 1 Up (UM)");
        Berths.createOrGetBerth("SI0417").setName("RMF Plat 5 Dn (DE)");
        Berths.createOrGetBerth("SI0418");
        Berths.createOrGetBerth("SI0419").setName("RMF Plat 3 (DM)");
        Berths.createOrGetBerth("SI0420");
        Berths.createOrGetBerth("SI0421");
        Berths.createOrGetBerth("SI0422");
        Berths.createOrGetBerth("SI0423");
        Berths.createOrGetBerth("SI0424");
        Berths.createOrGetBerth("SI0425");
        Berths.createOrGetBerth("SI0426");
        Berths.createOrGetBerth("SI0427");
        Berths.createOrGetBerth("SI0428");
        Berths.createOrGetBerth("SI0429");
        Berths.createOrGetBerth("SI0430");
        Berths.createOrGetBerth("SI0431").setName("GDP Plat 4 Dn (DE)");
        Berths.createOrGetBerth("SI0432");
        Berths.createOrGetBerth("SI0433");
        Berths.createOrGetBerth("SI0435").setName("GDP Plat 2 (DM)");
        Berths.createOrGetBerth("SI0436");
        Berths.createOrGetBerth("SI0438");
        Berths.createOrGetBerth("SI0439");
        Berths.createOrGetBerth("SI0440");
        Berths.createOrGetBerth("SI0441").addStepToBerth("SI0441", "SE0445", "SI0445", "suggest");
        Berths.createOrGetBerth("SI0442").setName("RMF Plat 4 (UE)");
        Berths.createOrGetBerth("SI0443").addStepToBerth("SI0443", "SE0449", "SI0449", "suggest");
        Berths.createOrGetBerth("SI0444").setName("RMF Plat 2 Up (UM)");
        Berths.createOrGetBerth("SI0446");
        Berths.createOrGetBerth("SI0448");
        Berths.createOrGetBerth("SI0450");
        Berths.createOrGetBerth("SI0452");
        Berths.createOrGetBerth("SI0454");
        Berths.createOrGetBerth("SI0456");
        Berths.createOrGetBerth("SI0458").setName("GDP Plat 4 Up (UM)");
        Berths.createOrGetBerth("SI0460").setName("GDP Plat 3 Up (UE)");
        Berths.createOrGetBerth("SI0462").setName("GDP Plat 1 (UM)");
        Berths.createOrGetBerth("SI0464");
        Berths.createOrGetBerth("SI0468");
        Berths.createOrGetBerth("SI0470");
        Berths.createOrGetBerth("SI0472");
        Berths.createOrGetBerth("SI0474");
        Berths.createOrGetBerth("SI0476");
        Berths.createOrGetBerth("SI5099");
        Berths.createOrGetBerth("SI5101").setName("CTH Plat 1 Dn (UM)");
        Berths.createOrGetBerth("SI5102").setName("RMF Plat 5 Up (DE)");
        Berths.createOrGetBerth("SI5104");
        Berths.createOrGetBerth("SI5105");
        Berths.createOrGetBerth("SI5107");
        Berths.createOrGetBerth("SI5100");
        Berths.createOrGetBerth("SI5111").setName("RMF Plat 2 Dn (UM)");
        Berths.createOrGetBerth("SI5113").setName("GDP Plat 3 Dn (UE)");
        Berths.createOrGetBerth("SI5114");
        Berths.createOrGetBerth("SI5116");
        Berths.createOrGetBerth("SI5125");
        Berths.createOrGetBerth("SI5139");
        Berths.createOrGetBerth("SIRCHS");
        Berths.createOrGetBerth("SIRGP1");
        Berths.createOrGetBerth("SIRGP2");
        Berths.createOrGetBerth("SIRGP3");
        Berths.createOrGetBerth("SIRGP4");
        Berths.createOrGetBerth("SIRGP5");
        Berths.createOrGetBerth("SIRGP6");
        Berths.createOrGetBerth("SIRGPC");
        Berths.createOrGetBerth("SIRGPL");
        Berths.createOrGetBerth("SIROM1").setName("RMF Plat 1");
        Berths.createOrGetBerth("SIRRED");
        Berths.createOrGetBerth("SIRROM").setName("RMF Plat 1");
        Berths.createOrGetBerth("SIUMIN");

        Berths.createOrGetBerth("SI0321");
        Berths.createOrGetBerth("SI0323");
        Berths.createOrGetBerth("SI0325");
        Berths.createOrGetBerth("SI0327").setName("MNP Plat 2 (DE)");
        Berths.createOrGetBerth("SI0329").setName("MNP Plat 4 (DM)");
        Berths.createOrGetBerth("SI0331");
        Berths.createOrGetBerth("SI0333");
        Berths.createOrGetBerth("SI0335");
        Berths.createOrGetBerth("SI0336").setName("MNP UPA");
        Berths.createOrGetBerth("SI0338").setName("MNP Plat 1 (UE)");
        Berths.createOrGetBerth("SI0339");
        Berths.createOrGetBerth("SI0340").setName("MNP Plat 3 (UM)");
        Berths.createOrGetBerth("SI0341");
        Berths.createOrGetBerth("SI0343");
        Berths.createOrGetBerth("SI0345");
        Berths.createOrGetBerth("SI0346");
        Berths.createOrGetBerth("SI0347");
        Berths.createOrGetBerth("SI0349").setName("IFD Plat 4 (DE)");
        Berths.createOrGetBerth("SI0350");
        Berths.createOrGetBerth("SI0351").setName("IFD Plat 2 (DM)");
        Berths.createOrGetBerth("SI0352");
        Berths.createOrGetBerth("SI0353");
        Berths.createOrGetBerth("SI0354");
        Berths.createOrGetBerth("SI0355");
        Berths.createOrGetBerth("SI0356");
        Berths.createOrGetBerth("SI0357");
        Berths.createOrGetBerth("SI0358");
        Berths.createOrGetBerth("SI0359");
        Berths.createOrGetBerth("SI0360");
        Berths.createOrGetBerth("SI0361");
        Berths.createOrGetBerth("SI0362").setName("IFD Plat 3 (UE)");
        Berths.createOrGetBerth("SI0363");
        Berths.createOrGetBerth("SI0364").setName("IFD Plat 1 (UM)");
        Berths.createOrGetBerth("SI0365").setName("SVK Plat 4 (DE)");
        Berths.createOrGetBerth("SI0367");
        Berths.createOrGetBerth("SI0368");
        Berths.createOrGetBerth("SI0369").setName("SVK Plat 2 (DM)");
        Berths.createOrGetBerth("SI0370");
        Berths.createOrGetBerth("SI0371");
        Berths.createOrGetBerth("SI0372");
        Berths.createOrGetBerth("SI0373");
        Berths.createOrGetBerth("SI0374");
        Berths.createOrGetBerth("SI0375");
        Berths.createOrGetBerth("SI0376");
        Berths.createOrGetBerth("SI0377").setName("GMY Plat 4 (DE)");
        Berths.createOrGetBerth("SI0378");
        Berths.createOrGetBerth("SI0379").setName("GMY Plat 2 (DM)");
        Berths.createOrGetBerth("SI0380");
        Berths.createOrGetBerth("SI0381");
        Berths.createOrGetBerth("SI0382");
        Berths.createOrGetBerth("SI0384");
        Berths.createOrGetBerth("SI0386");
        Berths.createOrGetBerth("SI0388");
        Berths.createOrGetBerth("SI0390").setName("SVK Palt 1 (UM)");
        Berths.createOrGetBerth("SI0392").setName("SVK Plat 3 (UE)");
        Berths.createOrGetBerth("SI0394");
        Berths.createOrGetBerth("SI0396");
        Berths.createOrGetBerth("SI0398");
        Berths.createOrGetBerth("SI0400").setName("GMY Plat 1 (UM)");
        Berths.createOrGetBerth("SI0402");
        Berths.createOrGetBerth("SI0404").setName("GMY Plat 3 (UE)");
        Berths.createOrGetBerth("SI0406");
        Berths.createOrGetBerth("SI0408");
        Berths.createOrGetBerth("SI5087");
        Berths.createOrGetBerth("SI5078");
        Berths.createOrGetBerth("SI5080");
        Berths.createOrGetBerth("SI5082");
        Berths.createOrGetBerth("SI5084");
        Berths.createOrGetBerth("SI5086");
        Berths.createOrGetBerth("SI5088");
        Berths.createOrGetBerth("SIA366").setName("IFD Plat 5a");
        Berths.createOrGetBerth("SIB366").setName("IFD Plat 5b");
        Berths.createOrGetBerth("SIICIN");
        Berths.createOrGetBerth("SIR366").setName("IFD Plat 5");
        Berths.createOrGetBerth("SIRAS1");
        Berths.createOrGetBerth("SIRAS2");
        Berths.createOrGetBerth("SIRAS3");
        Berths.createOrGetBerth("SIRAS4");
        Berths.createOrGetBerth("SIRAS5");
        Berths.createOrGetBerth("SIRIFC");
        Berths.createOrGetBerth("SIRIFL");
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Stratford + Liv St">
    private static void initStratford()
    {
        Berths.createOrGetBerth("LSR009").setName("LST Plat 1");
        Berths.createOrGetBerth("LSFC09").addAdjacentBerths("LSFA09", "LSFB09", "LSR009").setName("LST Plat 1");
        Berths.createOrGetBerth("LSFB09").addAdjacentBerths("LSFA09", "LSFC09", "LSR009").setName("LST Plat 1");
        Berths.createOrGetBerth("LSFA09").addAdjacentBerths("LSFB09", "LSFC09", "LSR009").setName("LST Plat 1");

        Berths.createOrGetBerth("LSR011").setName("LST Plat 2");
        Berths.createOrGetBerth("LSFC11").addAdjacentBerths("LSFA11", "LSFB11", "LSR011").setName("LST Plat 2");
        Berths.createOrGetBerth("LSFB11").addAdjacentBerths("LSFA11", "LSFB11", "LSR011").setName("LST Plat 2");
        Berths.createOrGetBerth("LSFA11").addAdjacentBerths("LSFA11", "LSFB11", "LSR011").setName("LST Plat 2");

        Berths.createOrGetBerth("LSR013").setName("LST Plat 3");
        Berths.createOrGetBerth("LSFC13").addAdjacentBerths("LSFA13", "LSFB13", "LSR013").setName("LST Plat 3");
        Berths.createOrGetBerth("LSFB13").addAdjacentBerths("LSFA13", "LSFB13", "LSR013").setName("LST Plat 3");
        Berths.createOrGetBerth("LSFA13").addAdjacentBerths("LSFA13", "LSFB13", "LSR013").setName("LST Plat 3");

        Berths.createOrGetBerth("LSR015").setName("LST Plat 4");
        Berths.createOrGetBerth("LSFC15").addAdjacentBerths("LSFA15", "LSFB15", "LSR015").setName("LST Plat 4");
        Berths.createOrGetBerth("LSFB15").addAdjacentBerths("LSFA15", "LSFB15", "LSR015").setName("LST Plat 4");
        Berths.createOrGetBerth("LSFA15").addAdjacentBerths("LSFA15", "LSFB15", "LSR015").setName("LST Plat 4");

        Berths.createOrGetBerth("LSR017").setName("LST Plat 5");
        Berths.createOrGetBerth("LSFC17").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "LS0055", "LS0057").setName("LST Plat 5");
        Berths.createOrGetBerth("LSFB17").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "LS0055", "LS0057").setName("LST Plat 5");
        Berths.createOrGetBerth("LSFA17").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "LS0055", "LS0057").setName("LST Plat 5");

        Berths.createOrGetBerth("LSR019").setName("LST Plat 6");
        Berths.createOrGetBerth("LSFC19").addAdjacentBerths("LSFA19", "LSFB19", "LSR019", "LS0055", "LS0057").setName("LST Plat 6");
        Berths.createOrGetBerth("LSFB19").addAdjacentBerths("LSFA19", "LSFB19", "LSR019", "LS0055", "LS0057").setName("LST Plat 6");
        Berths.createOrGetBerth("LSFA19").addAdjacentBerths("LSFA19", "LSFB19", "LSR019", "LS0055", "LS0057").setName("LST Plat 6");

        Berths.createOrGetBerth("LSR021").setName("LST Plat 7");
        Berths.createOrGetBerth("LSFC21").addAdjacentBerths("LSFA21", "LSFB21", "LSR021", "LS0055", "LS0057").setName("LST Plat 7");
        Berths.createOrGetBerth("LSFB21").addAdjacentBerths("LSFA21", "LSFB21", "LSR021", "LS0055", "LS0057").setName("LST Plat 7");
        Berths.createOrGetBerth("LSFA21").addAdjacentBerths("LSFA21", "LSFB21", "LSR021", "LS0055", "LS0057").setName("LST Plat 7");

        Berths.createOrGetBerth("LSR023").setName("LST Plat 8");
        Berths.createOrGetBerth("LSFC23").addAdjacentBerths("LSFA23", "LSFB23", "LSR023", "LS0055", "LS0057").setName("LST Plat 8");
        Berths.createOrGetBerth("LSFB23").addAdjacentBerths("LSFA23", "LSFB23", "LSR023", "LS0055", "LS0057").setName("LST Plat 8");
        Berths.createOrGetBerth("LSFA23").addAdjacentBerths("LSFA23", "LSFB23", "LSR023", "LS0055", "LS0057").setName("LST Plat 8");

        Berths.createOrGetBerth("LSR025").setName("LST Plat 9");
        Berths.createOrGetBerth("LSFC25").addAdjacentBerths("LSFA25", "LSFB25", "LSR025", "LS0027").setName("LST Plat 9");
        Berths.createOrGetBerth("LSFB25").addAdjacentBerths("LSFA25", "LSFC25", "LSR025", "LS0027").setName("LST Plat 9");
        Berths.createOrGetBerth("LSFA25").addAdjacentBerths("LSFB25", "LSFC25", "LSR025", "LS0027").setName("LST Plat 9");
        Berths.createOrGetBerth("LS0027").addAdjacentBerths("LSFA25", "LSFB25", "LSFC25", "LSR025");

        Berths.createOrGetBerth("LSR029").setName("LST Plat 10");
        Berths.createOrGetBerth("LSFC29").addAdjacentBerths("LSFA29", "LSFB29", "LSR029", "LS0031").setName("LST Plat 10");
        Berths.createOrGetBerth("LSFB29").addAdjacentBerths("LSFA29", "LSFC29", "LSR029", "LS0031").setName("LST Plat 10");
        Berths.createOrGetBerth("LSFA29").addAdjacentBerths("LSFB29", "LSFC29", "LSR029", "LS0031").setName("LST Plat 10");
        Berths.createOrGetBerth("LS0031").addAdjacentBerths("LSFA29", "LSFB29", "LSFC29", "LSR029");

        Berths.createOrGetBerth("LSR033").setName("LST Plat 11");
        Berths.createOrGetBerth("LSFC33").addAdjacentBerths("LBFA33", "LSFB33", "LSR033", "LS0035").setName("LST Plat 11");
        Berths.createOrGetBerth("LSFB33").addAdjacentBerths("LBFA33", "LSFC33", "LSR033", "LS0035").setName("LST Plat 11");
        Berths.createOrGetBerth("LSFA33").addAdjacentBerths("LBFB33", "LSFC33", "LSR033", "LS0035").setName("LST Plat 11");
        Berths.createOrGetBerth("LS0035").addAdjacentBerths("LSFA33", "LBFB33", "LSFC33", "LSR033");

        Berths.createOrGetBerth("LSR037").setName("LST Plat 12");
        Berths.createOrGetBerth("LSFC37").addAdjacentBerths("LBFA37", "LSFB37", "LSR037", "LS0039").setName("LST Plat 12");
        Berths.createOrGetBerth("LSFB37").addAdjacentBerths("LBFA37", "LSFC37", "LSR037", "LS0039").setName("LST Plat 12");
        Berths.createOrGetBerth("LSFA37").addAdjacentBerths("LBFB37", "LSFC37", "LSR037", "LS0039").setName("LST Plat 12");
        Berths.createOrGetBerth("LS0039").addAdjacentBerths("LSFA37", "LSFB37", "LSFC37", "LSR037");

        Berths.createOrGetBerth("LSR041").setName("LST Plat 13");
        Berths.createOrGetBerth("LSFC41").addAdjacentBerths("LBFA29", "LSFB29", "LS0031").setName("LST Plat 13");
        Berths.createOrGetBerth("LSFB41").addAdjacentBerths("LBFA29", "LSFC29", "LS0031").setName("LST Plat 13");
        Berths.createOrGetBerth("LSFA41").addAdjacentBerths("LBFB29", "LSFC29", "LS0031").setName("LST Plat 13");

        Berths.createOrGetBerth("LSR043").setName("LST Plat 14");
        Berths.createOrGetBerth("LSFC43").addAdjacentBerths("LBFA29", "LSFB29", "LS0031").setName("LST Plat 14");
        Berths.createOrGetBerth("LSFB43").addAdjacentBerths("LBFA29", "LSFC29", "LS0031").setName("LST Plat 14");
        Berths.createOrGetBerth("LSFA43").addAdjacentBerths("LBFB29", "LSFC29", "LS0031").setName("LST Plat 14");

        Berths.createOrGetBerth("LSR045").setName("LST Plat 15");
        Berths.createOrGetBerth("LSFC45").addAdjacentBerths("LBFA45", "LBFB45", "LSR045", "LS0047").setName("LST Plat 15");
        Berths.createOrGetBerth("LSFB45").addAdjacentBerths("LBFA45", "LBFC45", "LSR045", "LS0047").setName("LST Plat 15");
        Berths.createOrGetBerth("LSFA45").addAdjacentBerths("LBFB45", "LBFC45", "LSR045", "LS0047").setName("LST Plat 15");
        Berths.createOrGetBerth("LS0047").addAdjacentBerths("LSFA45", "LSFB45", "LSFC45", "LSR045");

        Berths.createOrGetBerth("LSR049").setName("LST Plat 16");
        Berths.createOrGetBerth("LSFC49").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 16");
        Berths.createOrGetBerth("LSFB49").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 16");
        Berths.createOrGetBerth("LSFA49").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 16");

        Berths.createOrGetBerth("LSR051").setName("LST Plat 17");
        Berths.createOrGetBerth("LSFC51").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 17");
        Berths.createOrGetBerth("LSFB51").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 17");
        Berths.createOrGetBerth("LSFA51").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 17");

        Berths.createOrGetBerth("LSR053").setName("LST Plat 18");
        Berths.createOrGetBerth("LSFC53").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 18");
        Berths.createOrGetBerth("LSFB53").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 18");
        Berths.createOrGetBerth("LSFA53").addAdjacentBerths("LSFA17", "LSFB17", "LSR017", "").setName("LST Plat 18");

        Berths.createOrGetBerth("LS0054");
        Berths.createOrGetBerth("LS0055");
        Berths.createOrGetBerth("LS0056");
        Berths.createOrGetBerth("LS0057");
        Berths.createOrGetBerth("LS0058");
        Berths.createOrGetBerth("LS0059");
        Berths.createOrGetBerth("LS0060");
        Berths.createOrGetBerth("LS0061");
        Berths.createOrGetBerth("LS0063");
        Berths.createOrGetBerth("LS0064");
        Berths.createOrGetBerth("LS0065");
        Berths.createOrGetBerth("LS0066");
        Berths.createOrGetBerth("LS0068");
        Berths.createOrGetBerth("LS0070");
        Berths.createOrGetBerth("LS0071");
        Berths.createOrGetBerth("LS0072");
        Berths.createOrGetBerth("LS0073");
        Berths.createOrGetBerth("LS0074");
        Berths.createOrGetBerth("LS0075");
        Berths.createOrGetBerth("LS0080");
        Berths.createOrGetBerth("LS0081");
        Berths.createOrGetBerth("LS0082");
        Berths.createOrGetBerth("LS0083"); // & 0082 (dual berth)
        Berths.createOrGetBerth("LS0084");
        Berths.createOrGetBerth("LS0085");
        Berths.createOrGetBerth("LS0086");
        Berths.createOrGetBerth("LS0090").setName("BET Plat 1 (DS)");
        Berths.createOrGetBerth("LS0091").setName("BET Plat 2 (US)");
        Berths.createOrGetBerth("LS0092").setName("BET UM");
        Berths.createOrGetBerth("LS0093").setName("BET DM");
        Berths.createOrGetBerth("LS0094").setName("BET UE");
        Berths.createOrGetBerth("LS0095").setName("BET DE");
        Berths.createOrGetBerth("LS0100");
        Berths.createOrGetBerth("LS0101");
        Berths.createOrGetBerth("LS0102");
        Berths.createOrGetBerth("LS0103");
        Berths.createOrGetBerth("LS0110");
        Berths.createOrGetBerth("LS0112");
        Berths.createOrGetBerth("LS0200");
        Berths.createOrGetBerth("LS0201").addStepToBerth("LS0201", "SI0221", "LS0221", "suggest");
        Berths.createOrGetBerth("LS0202");
        Berths.createOrGetBerth("LS0203").addStepToBerth("LS0203", "SI0223", "LS0223", "suggest");
        Berths.createOrGetBerth("LS0210");
        Berths.createOrGetBerth("LS0212");

        Berths.createOrGetBerth("SI0220").addStepToBerth("SI0220", "LS0210", "cancel", "suggest");
        Berths.createOrGetBerth("SI0221");
        Berths.createOrGetBerth("SI0222").addStepToBerth("SI0222", "LS0212", "cancel", "suggest");
        Berths.createOrGetBerth("SI0223");
        Berths.createOrGetBerth("SI0224");
        Berths.createOrGetBerth("SI0225");
        Berths.createOrGetBerth("SI0226");
        Berths.createOrGetBerth("SI0227");
        Berths.createOrGetBerth("SI0228");
        Berths.createOrGetBerth("SI0229");
        Berths.createOrGetBerth("SI0230");
        Berths.createOrGetBerth("SI0231");
        Berths.createOrGetBerth("SI0234");
        Berths.createOrGetBerth("SI0235");
        Berths.createOrGetBerth("SI0237");
        Berths.createOrGetBerth("SI0239");
        Berths.createOrGetBerth("SI0241");
        Berths.createOrGetBerth("SI0240");
        Berths.createOrGetBerth("SI0242");
        Berths.createOrGetBerth("SI0244");
        Berths.createOrGetBerth("SI0245");
        Berths.createOrGetBerth("SI0248");
        Berths.createOrGetBerth("SI0249");
        Berths.createOrGetBerth("SI0250");
        Berths.createOrGetBerth("SI0251");
        Berths.createOrGetBerth("SI0252");
        Berths.createOrGetBerth("SI0253");
        Berths.createOrGetBerth("SI0254");
        Berths.createOrGetBerth("SI0255");
        Berths.createOrGetBerth("SI0256");
        Berths.createOrGetBerth("SI0257");
        Berths.createOrGetBerth("SI0258");
        Berths.createOrGetBerth("SI0259");
        Berths.createOrGetBerth("SI0261");
        Berths.createOrGetBerth("SI0265");
        Berths.createOrGetBerth("SI0262").setName("SRA Plat 10 Up (DM)");
        Berths.createOrGetBerth("SI0263");
        Berths.createOrGetBerth("SI0264").setName("SRA Plat 9 Up (UM)");
        Berths.createOrGetBerth("SI0266").setName("SRA Plat 8 Up (DE)");
        Berths.createOrGetBerth("SI0267");
        Berths.createOrGetBerth("SI0268").setName("SRA Plat 5 Up (UE)");
        Berths.createOrGetBerth("SI0269");
        Berths.createOrGetBerth("SI0270").setName("SRA Plat 10 Up (DM)");
        Berths.createOrGetBerth("SI0273").setName("SRA Plat 10 Dn (DM)");
        Berths.createOrGetBerth("SI0274").setName("SRA Plat 12 Up (DTM)");
        Berths.createOrGetBerth("SI0275").setName("SRA Plat 9 Dn (UM)");
        Berths.createOrGetBerth("SI0276").setName("SRA Plat 11 Up (UTM)");
        Berths.createOrGetBerth("SI0277").setName("SRA Plat 8 Dn (DE)");
        Berths.createOrGetBerth("SI0278").setName("SRA Plat 10a Up (DA)");
        Berths.createOrGetBerth("SI0279").setName("SRA Plat 5 Dn (UE)");
        Berths.createOrGetBerth("SI0281").setName("SRA Plat 10a Dn (DA)");
        Berths.createOrGetBerth("SI0283");
        Berths.createOrGetBerth("SI0284");
        Berths.createOrGetBerth("SI0285");
        Berths.createOrGetBerth("SI0286");
        Berths.createOrGetBerth("SI0288");
        Berths.createOrGetBerth("SI0287");
        Berths.createOrGetBerth("SI0289").setName("MYL Plat 4 Dn (DM)");
        Berths.createOrGetBerth("SI0290").setName("MYL Plat 4 Up (DM)");
        Berths.createOrGetBerth("SI0291");
        Berths.createOrGetBerth("SI0292").setName("MYL Plat 3 (UM)");
        Berths.createOrGetBerth("SI0293").setName("MYL Plat 2 (DE)");
        Berths.createOrGetBerth("SI0294");
        Berths.createOrGetBerth("SI0295");
        Berths.createOrGetBerth("SI0296").setName("MYL Plat 1 (UE)");
        Berths.createOrGetBerth("SI0297");
        Berths.createOrGetBerth("SI0298");
        Berths.createOrGetBerth("SI0299");
        Berths.createOrGetBerth("SI0300");
        Berths.createOrGetBerth("SI0303");
        Berths.createOrGetBerth("SI0304");
        Berths.createOrGetBerth("SI0305");
        Berths.createOrGetBerth("SI0306").setName("FOG Plat 3 (UM)");
        Berths.createOrGetBerth("SI0307").setName("FOG Plat 2 (DE)");
        Berths.createOrGetBerth("SI0308");
        Berths.createOrGetBerth("SI0309").setName("FOG Plat 4 (DM)");
        Berths.createOrGetBerth("SI0310");
        Berths.createOrGetBerth("SI0313");
        Berths.createOrGetBerth("SI0314").setName("FOG Plat 1 (UE)");
        Berths.createOrGetBerth("SI0317");
        Berths.createOrGetBerth("SI0316");
        Berths.createOrGetBerth("SI0320");
        Berths.createOrGetBerth("SI0324");
        Berths.createOrGetBerth("SI0326");
        Berths.createOrGetBerth("SI0330");
        Berths.createOrGetBerth("SI0332");
        Berths.createOrGetBerth("SI0334");
        Berths.createOrGetBerth("SI0909");
        Berths.createOrGetBerth("SI0911");
        Berths.createOrGetBerth("SI1292");
        Berths.createOrGetBerth("SI1296");
        Berths.createOrGetBerth("SI1424");
        Berths.createOrGetBerth("SI5065");
        Berths.createOrGetBerth("SI5070");
        Berths.createOrGetBerth("SILSBY");
        Berths.createOrGetBerth("SIS697").setName("SRA Plat 12 Dn (DTM)");
        Berths.createOrGetBerth("SIS901").setName("SRA Plat 11 Dn (UTM)");
        Berths.createOrGetBerth("SIU518");
        Berths.createOrGetBerth("SI1294");

        Berths.createOrGetBerth("SI0032");
        Berths.createOrGetBerth("SI1003");
        Berths.createOrGetBerth("SIS700");
        Berths.createOrGetBerth("SIS701");
        Berths.createOrGetBerth("SIS703");
        Berths.createOrGetBerth("SIS704");
        Berths.createOrGetBerth("SIS705");
        Berths.createOrGetBerth("SIS706");
        Berths.createOrGetBerth("SIS707");
        Berths.createOrGetBerth("SIS708");
        Berths.createOrGetBerth("SIS712");
        Berths.createOrGetBerth("SIS713").addStepToBerth("SIS713", "WG1003", "SI1003", "suggest");
        Berths.createOrGetBerth("SIS715");
        Berths.createOrGetBerth("SIS716");
        Berths.createOrGetBerth("SIS717");
        Berths.createOrGetBerth("SIS718");
        Berths.createOrGetBerth("SIS767");
        Berths.createOrGetBerth("SIS770");
        Berths.createOrGetBerth("SIS772");
    }
    //</editor-fold>

    public SignalMap readFromMap()
    {
        for (Map.Entry pairs : Berths.getEntrySet())
        {
            Berth berth = (Berth) pairs.getValue();

            if (EastAngliaSignalMapServer.CClassMap.containsKey(pairs.getKey().toString()))
                berth.interpose(new Train(EastAngliaSignalMapServer.CClassMap.get(pairs.getKey().toString()), berth));
        }

        return this;
    }
}